<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        // Get country IDs by country_code
        $countryIds = DB::table('countries')
            ->whereIn('country_code', ['UK', 'US', 'AU', 'NZ', 'CA', 'DE', 'SA', 'AE'])
            ->pluck('id', 'country_code');

        $cities = [
            // United Kingdom (UK)
            [
                'name' => 'London',
                'ar_name' => 'لندن',
                'description' => 'London is the capital of the United Kingdom and a major global center for finance, education and culture.',
                'ar_description' => 'لندن عاصمة المملكة المتحدة وتعد مركزاً عالمياً مهماً للمال والتعليم والثقافة.',
                'country_id' => $countryIds['UK'],
                'latitude' => 51.5074000,
                'longitude' => -0.1278000,
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'Manchester',
                'ar_name' => 'مانشستر',
                'description' => 'Manchester is a lively UK city known for universities, sports culture and creative industries.',
                'ar_description' => 'مانشستر مدينة بريطانية حيوية تشتهر بجامعاتها وثقافة كرة القدم والصناعات الإبداعية.',
                'country_id' => $countryIds['UK'],
                'latitude' => 53.4808000,
                'longitude' => -2.2426000,
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Birmingham',
                'ar_name' => 'برمنغهام',
                'description' => 'Birmingham is a major city in central England with a diverse community and strong academic presence.',
                'ar_description' => 'برمنغهام مدينة كبرى في وسط إنجلترا تتميز بتنوع سكاني وحضور أكاديمي قوي.',
                'country_id' => $countryIds['UK'],
                'latitude' => 52.4862000,
                'longitude' => -1.8904000,
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Edinburgh',
                'ar_name' => 'إدنبرة',
                'description' => 'Edinburgh is the historic capital of Scotland, famous for its festivals and respected universities.',
                'ar_description' => 'إدنبرة عاصمة اسكتلندا التاريخية وتشتهر بمهرجاناتها وجامعاتها المرموقة.',
                'country_id' => $countryIds['UK'],
                'latitude' => 55.9533000,
                'longitude' => -3.1883000,
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Glasgow',
                'ar_name' => 'غلاسكو',
                'description' => 'Glasgow is a major Scottish city with a strong arts scene, modern campuses and friendly atmosphere.',
                'ar_description' => 'غلاسكو مدينة اسكتلندية كبرى تتميز بمشهد فني قوي وجامعات حديثة وجو ودود.',
                'country_id' => $countryIds['UK'],
                'latitude' => 55.8642000,
                'longitude' => -4.2518000,
                'display_order' => 5,
                'is_active' => true,
            ],

            // United States (US)
            [
                'name' => 'New York',
                'ar_name' => 'نيويورك',
                'description' => 'New York City is a world-famous metropolis and a leading destination for business, arts and education.',
                'ar_description' => 'نيويورك مدينة عالمية مشهورة وتعد وجهة رئيسية للأعمال والفنون والتعليم.',
                'country_id' => $countryIds['US'],
                'latitude' => 40.7128000,
                'longitude' => -74.0060000,
                'display_order' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'Los Angeles',
                'ar_name' => 'لوس أنجلِس',
                'description' => 'Los Angeles is a coastal US city known for entertainment industries, cultural diversity and sunny weather.',
                'ar_description' => 'لوس أنجلِس مدينة ساحلية أمريكية تشتهر بصناعة الترفيه وتنوعها الثقافي وطقسها المشمس.',
                'country_id' => $countryIds['US'],
                'latitude' => 34.0522000,
                'longitude' => -118.2437000,
                'display_order' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'Chicago',
                'ar_name' => 'شيكاغو',
                'description' => 'Chicago is an important city on Lake Michigan with strong universities, architecture and business districts.',
                'ar_description' => 'شيكاغو مدينة مهمة على بحيرة ميشيغان وتتميز بجامعات قوية وعمارة مميزة ومناطق أعمال نشطة.',
                'country_id' => $countryIds['US'],
                'latitude' => 41.8781000,
                'longitude' => -87.6298000,
                'display_order' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'Boston',
                'ar_name' => 'بوسطن',
                'description' => 'Boston is a historic US city widely recognized for its concentration of top-ranked universities.',
                'ar_description' => 'بوسطن مدينة أمريكية تاريخية معروفة بتركيز كبير من الجامعات المصنفة عالمياً.',
                'country_id' => $countryIds['US'],
                'latitude' => 42.3601000,
                'longitude' => -71.0589000,
                'display_order' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'San Francisco',
                'ar_name' => 'سان فرانسيسكو',
                'description' => 'San Francisco is a technology-oriented coastal city known for innovation, startups and scenic views.',
                'ar_description' => 'سان فرانسيسكو مدينة ساحلية تكنولوجية تشتهر بالابتكار والشركات الناشئة وإطلالاتها الجميلة.',
                'country_id' => $countryIds['US'],
                'latitude' => 37.7749000,
                'longitude' => -122.4194000,
                'display_order' => 10,
                'is_active' => true,
            ],

            // Australia (AU)
            [
                'name' => 'Sydney',
                'ar_name' => 'سيدني',
                'description' => 'Sydney is Australia’s largest city with a famous harbour, modern lifestyle and strong education options.',
                'ar_description' => 'سيدني أكبر مدن أستراليا وتشتهر بمينائها الشهير ونمط الحياة العصري وخيارات التعليم القوية.',
                'country_id' => $countryIds['AU'],
                'latitude' => -33.8688000,
                'longitude' => 151.2093000,
                'display_order' => 11,
                'is_active' => true,
            ],
            [
                'name' => 'Melbourne',
                'ar_name' => 'ملبورن',
                'description' => 'Melbourne is a cultural and educational hub known for universities, sports events and creative arts.',
                'ar_description' => 'ملبورن مركز ثقافي وتعليمي في أستراليا تشتهر بجامعاتها وفعالياتها الرياضية والفنون الإبداعية.',
                'country_id' => $countryIds['AU'],
                'latitude' => -37.8136000,
                'longitude' => 144.9631000,
                'display_order' => 12,
                'is_active' => true,
            ],
            [
                'name' => 'Brisbane',
                'ar_name' => 'بريزبن',
                'description' => 'Brisbane is a warm, riverside city offering a relaxed lifestyle and several modern university campuses.',
                'ar_description' => 'بريزبن مدينة دافئة على نهر تقدم نمط حياة مريحاً وعدة حرم جامعية حديثة.',
                'country_id' => $countryIds['AU'],
                'latitude' => -27.4698000,
                'longitude' => 153.0251000,
                'display_order' => 13,
                'is_active' => true,
            ],
            [
                'name' => 'Perth',
                'ar_name' => 'بيرث',
                'description' => 'Perth is a coastal city in Western Australia known for beaches, sunshine and growing educational sector.',
                'ar_description' => 'بيرث مدينة ساحلية في غرب أستراليا تشتهر بشواطئها وأشعة الشمس وقطاع تعليمي متنامٍ.',
                'country_id' => $countryIds['AU'],
                'latitude' => -31.9523000,
                'longitude' => 115.8613000,
                'display_order' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'Adelaide',
                'ar_name' => 'أديلايد',
                'description' => 'Adelaide is a medium-sized Australian city with a calm atmosphere and respected universities.',
                'ar_description' => 'أديلايد مدينة أسترالية متوسطة الحجم تتميز بأجواء هادئة وجامعات ذات سمعة جيدة.',
                'country_id' => $countryIds['AU'],
                'latitude' => -34.9285000,
                'longitude' => 138.6007000,
                'display_order' => 15,
                'is_active' => true,
            ],

            // New Zealand (NZ)
            [
                'name' => 'Auckland',
                'ar_name' => 'أوكلاند',
                'description' => 'Auckland is New Zealand’s largest city with a harbour, multicultural communities and major universities.',
                'ar_description' => 'أوكلاند أكبر مدن نيوزيلندا وتتميز بمينائها ومجتمعاتها متعددة الثقافات وجامعاتها الكبرى.',
                'country_id' => $countryIds['NZ'],
                'latitude' => -36.8485000,
                'longitude' => 174.7633000,
                'display_order' => 16,
                'is_active' => true,
            ],
            [
                'name' => 'Wellington',
                'ar_name' => 'ويلينغتون',
                'description' => 'Wellington is the capital of New Zealand, known for government institutions, arts and a compact city center.',
                'ar_description' => 'ويلينغتون عاصمة نيوزيلندا وتشتهر بالمؤسسات الحكومية والفنون ومركز المدينة الصغير النشط.',
                'country_id' => $countryIds['NZ'],
                'latitude' => -41.2865000,
                'longitude' => 174.7762000,
                'display_order' => 17,
                'is_active' => true,
            ],
            [
                'name' => 'Christchurch',
                'ar_name' => 'كرايستشيرش',
                'description' => 'Christchurch is a South Island city with English-style gardens, rebuilding projects and education providers.',
                'ar_description' => 'كرايستشيرش مدينة في الجزيرة الجنوبية تتميز بحدائق على الطراز الإنجليزي ومشاريع إعادة إعمار ومؤسسات تعليمية.',
                'country_id' => $countryIds['NZ'],
                'latitude' => -43.5321000,
                'longitude' => 172.6362000,
                'display_order' => 18,
                'is_active' => true,
            ],

            // Canada (CA)
            [
                'name' => 'Toronto',
                'ar_name' => 'تورونتو',
                'description' => 'Toronto is Canada’s largest city with a highly diverse population and many leading colleges and universities.',
                'ar_description' => 'تورونتو أكبر مدن كندا وتتميز بتنوع سكاني كبير والعديد من الكليات والجامعات المرموقة.',
                'country_id' => $countryIds['CA'],
                'latitude' => 43.6532000,
                'longitude' => -79.3832000,
                'display_order' => 19,
                'is_active' => true,
            ],
            [
                'name' => 'Vancouver',
                'ar_name' => 'فانكوفر',
                'description' => 'Vancouver is a Pacific coastal city known for mountains, ocean views and a high quality of life.',
                'ar_description' => 'فانكوفر مدينة ساحلية على المحيط الهادئ تشتهر بالجبال والإطلالات البحرية وجودة الحياة العالية.',
                'country_id' => $countryIds['CA'],
                'latitude' => 49.2827000,
                'longitude' => -123.1207000,
                'display_order' => 20,
                'is_active' => true,
            ],
            [
                'name' => 'Montreal',
                'ar_name' => 'مونتريال',
                'description' => 'Montreal is a bilingual Canadian city with European-style streets, festivals and strong academic institutions.',
                'ar_description' => 'مونتريال مدينة كندية ثنائية اللغة تتميز بشوارع على الطراز الأوروبي ومهرجانات ومؤسسات أكاديمية قوية.',
                'country_id' => $countryIds['CA'],
                'latitude' => 45.5017000,
                'longitude' => -73.5673000,
                'display_order' => 21,
                'is_active' => true,
            ],
            [
                'name' => 'Calgary',
                'ar_name' => 'كالغاري',
                'description' => 'Calgary is a growing city near the Rocky Mountains with a strong energy sector and universities.',
                'ar_description' => 'كالغاري مدينة نامية قرب جبال الروكي وتشتهر بقطاع الطاقة القوي وجامعاتها.',
                'country_id' => $countryIds['CA'],
                'latitude' => 51.0447000,
                'longitude' => -114.0719000,
                'display_order' => 22,
                'is_active' => true,
            ],
            [
                'name' => 'Ottawa',
                'ar_name' => 'أوتاوا',
                'description' => 'Ottawa is the capital of Canada, hosting federal institutions, museums and research-focused universities.',
                'ar_description' => 'أوتاوا عاصمة كندا وتضم مؤسسات اتحادية ومتاحف وجامعات تركز على البحث العلمي.',
                'country_id' => $countryIds['CA'],
                'latitude' => 45.4215000,
                'longitude' => -75.6972000,
                'display_order' => 23,
                'is_active' => true,
            ],

            // Germany (DE)
            [
                'name' => 'Berlin',
                'ar_name' => 'برلين',
                'description' => 'Berlin is the capital of Germany and a major European city for history, culture and international students.',
                'ar_description' => 'برلين عاصمة ألمانيا ومدينة أوروبية كبرى في مجالات التاريخ والثقافة واستقبال الطلاب الدوليين.',
                'country_id' => $countryIds['DE'],
                'latitude' => 52.5200000,
                'longitude' => 13.4050000,
                'display_order' => 24,
                'is_active' => true,
            ],
            [
                'name' => 'Munich',
                'ar_name' => 'ميونخ',
                'description' => 'Munich is a prosperous German city known for technology industries, universities and cultural events.',
                'ar_description' => 'ميونخ مدينة ألمانية مزدهرة تشتهر بصناعات التكنولوجيا وجامعاتها وفعالياتها الثقافية.',
                'country_id' => $countryIds['DE'],
                'latitude' => 48.1351000,
                'longitude' => 11.5820000,
                'display_order' => 25,
                'is_active' => true,
            ],
            [
                'name' => 'Frankfurt',
                'ar_name' => 'فرانكفورت',
                'description' => 'Frankfurt is a key financial center in Europe with a modern skyline and international transport links.',
                'ar_description' => 'فرانكفورت مركز مالي رئيسي في أوروبا يتميز بأفق حديث وروابط نقل دولية قوية.',
                'country_id' => $countryIds['DE'],
                'latitude' => 50.1109000,
                'longitude' => 8.6821000,
                'display_order' => 26,
                'is_active' => true,
            ],
            [
                'name' => 'Hamburg',
                'ar_name' => 'هامبورغ',
                'description' => 'Hamburg is a major port city in northern Germany with maritime heritage and creative industries.',
                'ar_description' => 'هامبورغ مدينة ميناء كبرى في شمال ألمانيا تشتهر بتراثها البحري والصناعات الإبداعية.',
                'country_id' => $countryIds['DE'],
                'latitude' => 53.5511000,
                'longitude' => 9.9937000,
                'display_order' => 27,
                'is_active' => true,
            ],
            [
                'name' => 'Cologne',
                'ar_name' => 'كولونيا',
                'description' => 'Cologne is a historic German city on the Rhine River, famous for its cathedral and vibrant student life.',
                'ar_description' => 'كولونيا مدينة ألمانية تاريخية على نهر الراين تشتهر بكاتدرائيتها وحياة الطلبة النشطة.',
                'country_id' => $countryIds['DE'],
                'latitude' => 50.9375000,
                'longitude' => 6.9603000,
                'display_order' => 28,
                'is_active' => true,
            ],

            // Saudi Arabia (SA)
            [
                'name' => 'Riyadh',
                'ar_name' => 'الرياض',
                'description' => 'Riyadh is the capital of Saudi Arabia and a modern city with government institutions and universities.',
                'ar_description' => 'الرياض عاصمة المملكة العربية السعودية ومدينة حديثة تضم مؤسسات حكومية وجامعات متعددة.',
                'country_id' => $countryIds['SA'],
                'latitude' => 24.7136000,
                'longitude' => 46.6753000,
                'display_order' => 29,
                'is_active' => true,
            ],
            [
                'name' => 'Jeddah',
                'ar_name' => 'جدة',
                'description' => 'Jeddah is a major coastal city on the Red Sea, known as a commercial gateway and travel hub.',
                'ar_description' => 'جدة مدينة ساحلية كبرى على البحر الأحمر وتعد بوابة تجارية ومركزاً مهماً للسفر.',
                'country_id' => $countryIds['SA'],
                'latitude' => 21.4858000,
                'longitude' => 39.1925000,
                'display_order' => 30,
                'is_active' => true,
            ],
            [
                'name' => 'Dammam',
                'ar_name' => 'الدمام',
                'description' => 'Dammam is an eastern Saudi city central to the oil industry and connected to nearby Gulf states.',
                'ar_description' => 'الدمام مدينة شرقية في السعودية تعد مركزاً رئيسياً لصناعة النفط وترتبط بدول الخليج المجاورة.',
                'country_id' => $countryIds['SA'],
                'latitude' => 26.4207000,
                'longitude' => 50.0888000,
                'display_order' => 31,
                'is_active' => true,
            ],
            [
                'name' => 'Medina',
                'ar_name' => 'المدينة المنورة',
                'description' => 'Medina is a holy city in Islam and an important destination for visitors and religious students.',
                'ar_description' => 'المدينة المنورة مدينة مقدسة في الإسلام ووجهة مهمة للزوار وطلاب العلوم الشرعية.',
                'country_id' => $countryIds['SA'],
                'latitude' => 24.5247000,
                'longitude' => 39.5692000,
                'display_order' => 32,
                'is_active' => true,
            ],
            [
                'name' => 'Mecca',
                'ar_name' => 'مكة المكرمة',
                'description' => 'Mecca is the holiest city in Islam and receives millions of pilgrims each year from around the world.',
                'ar_description' => 'مكة المكرمة أقدس مدينة في الإسلام وتستقبل ملايين الحجاج سنوياً من مختلف أنحاء العالم.',
                'country_id' => $countryIds['SA'],
                'latitude' => 21.3891000,
                'longitude' => 39.8579000,
                'display_order' => 33,
                'is_active' => true,
            ],

            // United Arab Emirates (AE)
            [
                'name' => 'Dubai',
                'ar_name' => 'دبي',
                'description' => 'Dubai is a global city in the UAE known for modern skyline, tourism, business centers and international schools.',
                'ar_description' => 'دبي مدينة عالمية في الإمارات تشتهر بأفقها الحديث والسياحة ومراكز الأعمال والمدارس الدولية.',
                'country_id' => $countryIds['AE'],
                'latitude' => 25.2048000,
                'longitude' => 55.2708000,
                'display_order' => 34,
                'is_active' => true,
            ],
            [
                'name' => 'Abu Dhabi',
                'ar_name' => 'أبوظبي',
                'description' => 'Abu Dhabi is the capital of the UAE, combining government institutions, cultural sites and universities.',
                'ar_description' => 'أبوظبي عاصمة دولة الإمارات وتجمع بين المؤسسات الحكومية والمعالم الثقافية والجامعات.',
                'country_id' => $countryIds['AE'],
                'latitude' => 24.4539000,
                'longitude' => 54.3773000,
                'display_order' => 35,
                'is_active' => true,
            ],
            [
                'name' => 'Sharjah',
                'ar_name' => 'الشارقة',
                'description' => 'Sharjah is known as a cultural capital of the UAE with museums, universities and family-friendly communities.',
                'ar_description' => 'الشارقة تُعرف بالعاصمة الثقافية للإمارات وتضم متاحف وجامعات ومجتمعات مناسبة للعائلات.',
                'country_id' => $countryIds['AE'],
                'latitude' => 25.3463000,
                'longitude' => 55.4209000,
                'display_order' => 36,
                'is_active' => true,
            ],
            [
                'name' => 'Ajman',
                'ar_name' => 'عجمان',
                'description' => 'Ajman is a smaller emirate offering a quieter lifestyle while remaining close to Dubai and Sharjah.',
                'ar_description' => 'عجمان إمارة صغيرة توفر نمط حياة أكثر هدوءاً مع قربها من دبي والشارقة.',
                'country_id' => $countryIds['AE'],
                'latitude' => 25.4052000,
                'longitude' => 55.5136000,
                'display_order' => 37,
                'is_active' => true,
            ],
            [
                'name' => 'Al Ain',
                'ar_name' => 'العين',
                'description' => 'Al Ain is an inland city of the UAE known for its greenery, heritage sites and university campuses.',
                'ar_description' => 'العين مدينة داخلية في الإمارات تشتهر بخضرتها ومعالمها التراثية وحرمها الجامعي.',
                'country_id' => $countryIds['AE'],
                'latitude' => 24.1302000,
                'longitude' => 55.8023000,
                'display_order' => 38,
                'is_active' => true,
            ],
        ];

        DB::table('cities')->insert($cities);
    }
}
