<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                'name' => 'Germany',
                'ar_name' => 'ألمانيا',
                'flag' => 'assets/flags/de.svg',
                'country_code' => 'DE',
                'currency_code' => 'EUR',
                'phone_code' => '+49',
                'description' => 'Germany is a major European country known for its strong economy, rich cultural history and high quality education.',
                'ar_description' => 'ألمانيا دولة أوروبية كبرى تشتهر باقتصاد قوي وتاريخ ثقافي غني ومعايير تعليم عالية.',
                'capital' => 'Berlin',
                'continent' => 'Europe',
                'display_order' => 1,
                'is_active' => true,
            ],
            [
                'name' => 'France',
                'ar_name' => 'فرنسا',
                'flag' => 'assets/flags/fr.svg',
                'country_code' => 'FR',
                'currency_code' => 'EUR',
                'phone_code' => '+33',
                'description' => 'France is a leading European destination famous for Paris, its arts, diverse cuisine and attractive study opportunities.',
                'ar_description' => 'فرنسا وجهة سياحية عالمية تشتهر بباريس وفنونها الراقية ومطبخها المتنوع وجودة التعليم.',
                'capital' => 'Paris',
                'continent' => 'Europe',
                'display_order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'Italy',
                'ar_name' => 'إيطاليا',
                'flag' => 'assets/flags/it.svg',
                'country_code' => 'IT',
                'currency_code' => 'EUR',
                'phone_code' => '+39',
                'description' => 'Italy is a Mediterranean country known for its ancient history, iconic cities and a wide range of academic disciplines.',
                'ar_description' => 'إيطاليا دولة متوسطية معروفة بتاريخ إمبراطوري عريق ومدن سياحية جميلة وتخصصات تعليمية متنوعة.',
                'capital' => 'Rome',
                'continent' => 'Europe',
                'display_order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Spain',
                'ar_name' => 'إسبانيا',
                'flag' => 'assets/flags/es.svg',
                'country_code' => 'ES',
                'currency_code' => 'EUR',
                'phone_code' => '+34',
                'description' => 'Spain is a vibrant European country with rich culture, coastal cities and popular programs for international students.',
                'ar_description' => 'إسبانيا بلد أوروبي حيوي يتميز بثقافة غنية ومدن ساحلية جميلة وبرامج دراسية جذابة للطلاب الدوليين.',
                'capital' => 'Madrid',
                'continent' => 'Europe',
                'display_order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'Netherlands',
                'ar_name' => 'هولندا',
                'flag' => 'assets/flags/nl.svg',
                'country_code' => 'NL',
                'currency_code' => 'EUR',
                'phone_code' => '+31',
                'description' => 'The Netherlands is known for its canals, modern cities and strong universities that attract many international students.',
                'ar_description' => 'هولندا دولة مسطحة تشتهر بقنواتها وطواحين الهواء وجامعاتها القوية وبرامجها الموجهة للطلاب الأجانب.',
                'capital' => 'Amsterdam',
                'continent' => 'Europe',
                'display_order' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'Switzerland',
                'ar_name' => 'سويسرا',
                'flag' => 'assets/flags/ch.svg',
                'country_code' => 'CH',
                'currency_code' => 'CHF',
                'phone_code' => '+41',
                'description' => 'Switzerland is a peaceful Alpine country known for high living standards, respected universities and a safe environment.',
                'ar_description' => 'سويسرا دولة جبلية هادئة تشتهر بجودة المعيشة العالية والجامعات المرموقة والبيئة الآمنة للطلاب.',
                'capital' => 'Bern',
                'continent' => 'Europe',
                'display_order' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'Sweden',
                'ar_name' => 'السويد',
                'flag' => 'assets/flags/se.svg',
                'country_code' => 'SE',
                'currency_code' => 'SEK',
                'phone_code' => '+46',
                'description' => 'Sweden is an advanced Nordic country offering high quality education, beautiful nature and a supportive social system.',
                'ar_description' => 'السويد دولة اسكندنافية متقدمة تقدم تعليماً عالي الجودة وبيئة طبيعية خلابة ونظاماً اجتماعياً داعماً.',
                'capital' => 'Stockholm',
                'continent' => 'Europe',
                'display_order' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'Norway',
                'ar_name' => 'النرويج',
                'flag' => 'assets/flags/no.svg',
                'country_code' => 'NO',
                'currency_code' => 'NOK',
                'phone_code' => '+47',
                'description' => 'Norway is a Scandinavian country with stunning nature, strong education system and a safe environment for students.',
                'ar_description' => 'النرويج بلد اسكندنافي غني بالموارد الطبيعية يوفر نظام تعليم قوي وبيئة آمنة وطبيعة مدهشة.',
                'capital' => 'Oslo',
                'continent' => 'Europe',
                'display_order' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'Ireland',
                'ar_name' => 'أيرلندا',
                'flag' => 'assets/flags/ie.svg',
                'country_code' => 'IE',
                'currency_code' => 'EUR',
                'phone_code' => '+353',
                'description' => 'Ireland is a green island nation with historic universities, lively cities and attractive options for international students.',
                'ar_description' => 'أيرلندا جزيرة خضراء جميلة تضم جامعات عريقة ومدناً مفعمة بالحياة وفرصاً جيدة للطلاب الدوليين.',
                'capital' => 'Dublin',
                'continent' => 'Europe',
                'display_order' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'Denmark',
                'ar_name' => 'الدنمارك',
                'flag' => 'assets/flags/dk.svg',
                'country_code' => 'DK',
                'currency_code' => 'DKK',
                'phone_code' => '+45',
                'description' => 'Denmark is a modern Scandinavian country known for creative design, advanced education and high quality of life.',
                'ar_description' => 'الدنمارك دولة اسكندنافية حديثة تشتهر بتصميمها الإبداعي وتعليمها المتقدم ومستوى المعيشة المرتفع.',
                'capital' => 'Copenhagen',
                'continent' => 'Europe',
                'display_order' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'United Kingdom',
                'ar_name' => 'المملكة المتحدة',
                'flag' => 'assets/flags/gb.svg',
                'country_code' => 'UK',
                'currency_code' => 'GBP',
                'phone_code' => '+44',
                'description' => 'The United Kingdom is a leading destination for higher education with globally recognized universities and diverse cities.',
                'ar_description' => 'المملكة المتحدة وجهة رائدة للتعليم العالي بجامعات معترف بها عالمياً ومدن متنوعة.',
                'capital' => 'London',
                'continent' => 'Europe',
                'display_order' => 11,
                'is_active' => true,
            ],
            [
                'name' => 'Egypt',
                'ar_name' => 'مصر',
    'flag' => 'assets/flags/eg.svg',
    'country_code' => 'EG',
    'currency_code' => 'EGP',
    'phone_code' => '+20',
    'description' => 'Egypt is a historic African nation known for its ancient civilization, cultural heritage and strategic location.',
    'ar_description' => 'مصر دولة إفريقية تاريخية تشتهر بحضارتها القديمة وتراثها الثقافي وموقعها الاستراتيجي.',
    'capital' => 'Cairo',
    'continent' => 'Africa',
    'display_order' => 1,
    'is_active' => true,
],
[
    'name' => 'South Africa',
    'ar_name' => 'جنوب أفريقيا',
    'flag' => 'assets/flags/za.svg',
    'country_code' => 'ZA',
    'currency_code' => 'ZAR',
    'phone_code' => '+27',
    'description' => 'South Africa is a diverse country with modern cities, rich wildlife and a strong education environment.',
    'ar_description' => 'جنوب أفريقيا دولة متنوعة تتميز بمدن حديثة وحياة برية غنية وبيئة تعليمية قوية.',
    'capital' => 'Pretoria',
    'continent' => 'Africa',
    'display_order' => 2,
    'is_active' => true,
],
[
    'name' => 'Nigeria',
    'ar_name' => 'نيجيريا',
    'flag' => 'assets/flags/ng.svg',
    'country_code' => 'NG',
    'currency_code' => 'NGN',
    'phone_code' => '+234',
    'description' => 'Nigeria is Africa’s most populous nation with a dynamic culture, growing economy and emerging education sector.',
    'ar_description' => 'نيجيريا أكبر دولة إفريقية من حيث عدد السكان بثقافة ديناميكية واقتصاد متنامٍ وقطاع تعليمي ناشئ.',
    'capital' => 'Abuja',
    'continent' => 'Africa',
    'display_order' => 3,
    'is_active' => true,
],
[
    'name' => 'Kenya',
    'ar_name' => 'كينيا',
    'flag' => 'assets/flags/ke.svg',
    'country_code' => 'KE',
    'currency_code' => 'KES',
    'phone_code' => '+254',
    'description' => 'Kenya is known for its stunning landscapes, wildlife reserves and vibrant growing cities.',
    'ar_description' => 'كينيا دولة مشهورة بمناظرها الطبيعية الخلابة ومحمياتها البرية ومدنها المتنامية.',
    'capital' => 'Nairobi',
    'continent' => 'Africa',
    'display_order' => 4,
    'is_active' => true,
],
[
    'name' => 'Morocco',
    'ar_name' => 'المغرب',
    'flag' => 'assets/flags/ma.svg',
    'country_code' => 'MA',
    'currency_code' => 'MAD',
    'phone_code' => '+212',
    'description' => 'Morocco blends Arab, Berber and European influences with historic cities and unique landscapes.',
    'ar_description' => 'المغرب يجمع بين التأثيرات العربية والأمازيغية والأوروبية مع مدن تاريخية ومناظر طبيعية مميزة.',
    'capital' => 'Rabat',
    'continent' => 'Africa',
    'display_order' => 5,
    'is_active' => true,
],
[
    'name' => 'Algeria',
    'ar_name' => 'الجزائر',
    'flag' => 'assets/flags/dz.svg',
    'country_code' => 'DZ',
    'currency_code' => 'DZD',
    'phone_code' => '+213',
    'description' => 'Algeria is a large North African nation with desert landscapes, coastal cities and cultural traditions.',
    'ar_description' => 'الجزائر دولة إفريقية كبيرة ذات صحاري واسعة ومدن ساحلية وتقاليد ثقافية عريقة.',
    'capital' => 'Algiers',
    'continent' => 'Africa',
    'display_order' => 6,
    'is_active' => true,
],
[
    'name' => 'Tunisia',
    'ar_name' => 'تونس',
    'flag' => 'assets/flags/tn.svg',
    'country_code' => 'TN',
    'currency_code' => 'TND',
    'phone_code' => '+216',
    'description' => 'Tunisia offers Mediterranean coastlines, rich history and a welcoming environment for visitors.',
    'ar_description' => 'تونس دولة متوسطية تتميز بسواحل جميلة وتاريخ غني وبيئة مضيافة.',
    'capital' => 'Tunis',
    'continent' => 'Africa',
    'display_order' => 7,
    'is_active' => true,
],
[
    'name' => 'Ethiopia',
    'ar_name' => 'إثيوبيا',
    'flag' => 'assets/flags/et.svg',
    'country_code' => 'ET',
    'currency_code' => 'ETB',
    'phone_code' => '+251',
    'description' => 'Ethiopia is one of the world’s oldest civilizations known for its cultural identity and unique heritage.',
    'ar_description' => 'إثيوبيا من أقدم الحضارات في العالم وتشتهر بهويتها الثقافية وتراثها الفريد.',
    'capital' => 'Addis Ababa',
    'continent' => 'Africa',
    'display_order' => 8,
    'is_active' => true,
],
[
    'name' => 'Ghana',
    'ar_name' => 'غانا',
    'flag' => 'assets/flags/gh.svg',
    'country_code' => 'GH',
    'currency_code' => 'GHS',
    'phone_code' => '+233',
    'description' => 'Ghana is a peaceful West African nation known for its friendly people, culture and stable growth.',
    'ar_description' => 'غانا دولة إفريقية مسالمة تشتهر بشعبها الودود وثقافتها ونموها المستقر.',
    'capital' => 'Accra',
    'continent' => 'Africa',
    'display_order' => 9,
    'is_active' => true,
],
[
    'name' => 'Uganda',
    'ar_name' => 'أوغندا',
    'flag' => 'assets/flags/ug.svg',
    'country_code' => 'UG',
    'currency_code' => 'UGX',
    'phone_code' => '+256',
    'description' => 'Uganda is known for its natural beauty, wildlife and warm communities spread across the country.',
    'ar_description' => 'أوغندا تشتهر بجمالها الطبيعي وحياتها البرية ومجتمعاتها الدافئة.',
    'capital' => 'Kampala',
    'continent' => 'Africa',
    'display_order' => 10,
    'is_active' => true,
],
[
    'name' => 'United States',
    'ar_name' => 'الولايات المتحدة',
    'flag' => 'assets/flags/us.svg',
    'country_code' => 'US',
    'currency_code' => 'USD',
    'phone_code' => '+1',
    'description' => 'The United States is a large and diverse nation known for innovation, global influence and top-ranked universities.',
    'ar_description' => 'الولايات المتحدة دولة كبيرة ومتنوعة تشتهر بالابتكار والتأثير العالمي والجامعات المرموقة.',
    'capital' => 'Washington, D.C.',
    'continent' => 'North America',
    'display_order' => 1,
    'is_active' => true,
],
[
    'name' => 'Canada',
    'ar_name' => 'كندا',
    'flag' => 'assets/flags/ca.svg',
    'country_code' => 'CA',
    'currency_code' => 'CAD',
    'phone_code' => '+1',
    'description' => 'Canada is known for its safety, multicultural cities, high education standards and beautiful natural scenery.',
    'ar_description' => 'كندا دولة آمنة مع مدن متعددة الثقافات وتعليم عالي الجودة ومناظر طبيعية خلابة.',
    'capital' => 'Ottawa',
    'continent' => 'North America',
    'display_order' => 2,
    'is_active' => true,
],
[
    'name' => 'Mexico',
    'ar_name' => 'المكسيك',
    'flag' => 'assets/flags/mx.svg',
    'country_code' => 'MX',
    'currency_code' => 'MXN',
    'phone_code' => '+52',
    'description' => 'Mexico is rich in history, culture and cuisine with vibrant cities and strong regional traditions.',
    'ar_description' => 'المكسيك دولة غنية بالتاريخ والثقافة والمأكولات مع مدن نابضة وتقاليد محلية قوية.',
    'capital' => 'Mexico City',
    'continent' => 'North America',
    'display_order' => 3,
    'is_active' => true,
],
[
    'name' => 'Costa Rica',
    'ar_name' => 'كوستاريكا',
    'flag' => 'assets/flags/cr.svg',
    'country_code' => 'CR',
    'currency_code' => 'CRC',
    'phone_code' => '+506',
    'description' => 'Costa Rica is known for its peaceful society, tropical nature and strong environmental policies.',
    'ar_description' => 'كوستاريكا دولة معروفة بطبيعتها الاستوائية وسياساتها البيئية ومجتمعها المسالم.',
    'capital' => 'San José',
    'continent' => 'North America',
    'display_order' => 4,
    'is_active' => true,
],
[
    'name' => 'Panama',
    'ar_name' => 'بنما',
    'flag' => 'assets/flags/pa.svg',
    'country_code' => 'PA',
    'currency_code' => 'PAB',
    'phone_code' => '+507',
    'description' => 'Panama connects two continents and is known for its famous canal, active economy and diverse culture.',
    'ar_description' => 'بنما تربط بين قارتين وتشتهر بقناتها الشهيرة واقتصادها النشط وثقافتها المتنوعة.',
    'capital' => 'Panama City',
    'continent' => 'North America',
    'display_order' => 5,
    'is_active' => true,
],
[
    'name' => 'Cuba',
    'ar_name' => 'كوبا',
    'flag' => 'assets/flags/cu.svg',
    'country_code' => 'CU',
    'currency_code' => 'CUP',
    'phone_code' => '+53',
    'description' => 'Cuba offers a rich Caribbean culture, colonial history and vibrant music and arts traditions.',
    'ar_description' => 'كوبا دولة كاريبية ذات ثقافة غنية وتاريخ استعماري وتقاليد موسيقية مفعمة بالحياة.',
    'capital' => 'Havana',
    'continent' => 'North America',
    'display_order' => 6,
    'is_active' => true,
],
[
    'name' => 'Honduras',
    'ar_name' => 'هندوراس',
    'flag' => 'assets/flags/hn.svg',
    'country_code' => 'HN',
    'currency_code' => 'HNL',
    'phone_code' => '+504',
    'description' => 'Honduras features tropical landscapes, historic towns and a warm Caribbean cultural influence.',
    'ar_description' => 'هندوراس تتميز بمناظرها الاستوائية ومدنها التاريخية وتأثيرها الثقافي الكاريبي.',
    'capital' => 'Tegucigalpa',
    'continent' => 'North America',
    'display_order' => 7,
    'is_active' => true,
],
[
    'name' => 'Guatemala',
    'ar_name' => 'غواتيمالا',
    'flag' => 'assets/flags/gt.svg',
    'country_code' => 'GT',
    'currency_code' => 'GTQ',
    'phone_code' => '+502',
    'description' => 'Guatemala is known for Mayan heritage, volcanic landscapes and colorful cultural traditions.',
    'ar_description' => 'غواتيمالا تشتهر بتراث المايا ومناظرها البركانية وتقاليدها الثقافية الملونة.',
    'capital' => 'Guatemala City',
    'continent' => 'North America',
    'display_order' => 8,
    'is_active' => true,
],
[
    'name' => 'Jamaica',
    'ar_name' => 'جامايكا',
    'flag' => 'assets/flags/jm.svg',
    'country_code' => 'JM',
    'currency_code' => 'JMD',
    'phone_code' => '+1-876',
    'description' => 'Jamaica is known worldwide for its music, tropical beaches and welcoming Caribbean culture.',
    'ar_description' => 'جامايكا مشهورة عالمياً بموسيقاها وشواطئها الاستوائية وثقافتها الكاريبية المضيافة.',
    'capital' => 'Kingston',
    'continent' => 'North America',
    'display_order' => 9,
    'is_active' => true,
],
[
    'name' => 'Dominican Republic',
    'ar_name' => 'جمهورية الدومينيكان',
    'flag' => 'assets/flags/do.svg',
    'country_code' => 'DO',
    'currency_code' => 'DOP',
    'phone_code' => '+1-809',
    'description' => 'The Dominican Republic offers stunning beaches, cultural heritage and vibrant tourism.',
    'ar_description' => 'جمهورية الدومينيكان تتميز بشواطئ رائعة وتراث ثقافي وسياحة نابضة بالحياة.',
    'capital' => 'Santo Domingo',
    'continent' => 'North America',
    'display_order' => 10,
    'is_active' => true,
],
[
    'name' => 'Brazil',
    'ar_name' => 'البرازيل',
    'flag' => 'assets/flags/br.svg',
    'country_code' => 'BR',
    'currency_code' => 'BRL',
    'phone_code' => '+55',
    'description' => 'Brazil is South America’s largest country known for its festivals, rainforest and dynamic cities.',
    'ar_description' => 'البرازيل أكبر دولة في أمريكا الجنوبية وتشتهر بمهرجاناتها وغابات الأمازون ومدنها الديناميكية.',
    'capital' => 'Brasília',
    'continent' => 'South America',
    'display_order' => 1,
    'is_active' => true,
],
[
    'name' => 'Argentina',
    'ar_name' => 'الأرجنتين',
    'flag' => 'assets/flags/ar.svg',
    'country_code' => 'AR',
    'currency_code' => 'ARS',
    'phone_code' => '+54',
    'description' => 'Argentina is known for its European-style cities, diverse landscapes and cultural traditions.',
    'ar_description' => 'الأرجنتين دولة تتميز بمدنها ذات الطابع الأوروبي ومناظرها المتنوعة وتقاليدها الثقافية.',
    'capital' => 'Buenos Aires',
    'continent' => 'South America',
    'display_order' => 2,
    'is_active' => true,
],
[
    'name' => 'Chile',
    'ar_name' => 'تشيلي',
    'flag' => 'assets/flags/cl.svg',
    'country_code' => 'CL',
    'currency_code' => 'CLP',
    'phone_code' => '+56',
    'description' => 'Chile stretches along the Pacific coast with unique geography, modern cities and strong education.',
    'ar_description' => 'تشيلي تمتد على ساحل المحيط الهادئ وتتميز بجغرافيا فريدة ومدن حديثة وتعليم قوي.',
    'capital' => 'Santiago',
    'continent' => 'South America',
    'display_order' => 3,
    'is_active' => true,
],
[
    'name' => 'Colombia',
    'ar_name' => 'كولومبيا',
    'flag' => 'assets/flags/co.svg',
    'country_code' => 'CO',
    'currency_code' => 'COP',
    'phone_code' => '+57',
    'description' => 'Colombia offers beautiful landscapes, friendly culture and vibrant music and arts traditions.',
    'ar_description' => 'كولومبيا دولة تتميز بمناظر جميلة وثقافة ودودة وتقاليد موسيقية نابضة.',
    'capital' => 'Bogotá',
    'continent' => 'South America',
    'display_order' => 4,
    'is_active' => true,
],
[
    'name' => 'Peru',
    'ar_name' => 'بيرو',
    'flag' => 'assets/flags/pe.svg',
    'country_code' => 'PE',
    'currency_code' => 'PEN',
    'phone_code' => '+51',
    'description' => 'Peru is known for its ancient Inca heritage, mountainous landscapes and unique culture.',
    'ar_description' => 'بيرو تشتهر بتراث حضارة الإنكا القديم ومناظرها الجبلية وثقافتها الفريدة.',
    'capital' => 'Lima',
    'continent' => 'South America',
    'display_order' => 5,
    'is_active' => true,
],
[
    'name' => 'Uruguay',
    'ar_name' => 'أوروغواي',
    'flag' => 'assets/flags/uy.svg',
    'country_code' => 'UY',
    'currency_code' => 'UYU',
    'phone_code' => '+598',
    'description' => 'Uruguay is a peaceful South American country known for stability, culture and coastal cities.',
    'ar_description' => 'أوروغواي دولة مسالمة في أمريكا الجنوبية تشتهر بالاستقرار والثقافة والمدن الساحلية.',
    'capital' => 'Montevideo',
    'continent' => 'South America',
    'display_order' => 6,
    'is_active' => true,
],
[
    'name' => 'Ecuador',
    'ar_name' => 'الإكوادور',
    'flag' => 'assets/flags/ec.svg',
    'country_code' => 'EC',
    'currency_code' => 'USD',
    'phone_code' => '+593',
    'description' => 'Ecuador is known for the Galápagos Islands, rich biodiversity and historic cities.',
    'ar_description' => 'الإكوادور تشتهر بجزر غالاباغوس وتنوعها الحيوي ومدنها التاريخية.',
    'capital' => 'Quito',
    'continent' => 'South America',
    'display_order' => 7,
    'is_active' => true,
],
[
    'name' => 'Bolivia',
    'ar_name' => 'بوليفيا',
    'flag' => 'assets/flags/bo.svg',
    'country_code' => 'BO',
    'currency_code' => 'BOB',
    'phone_code' => '+591',
    'description' => 'Bolivia features high-altitude landscapes, indigenous traditions and unique cultural identity.',
    'ar_description' => 'بوليفيا تتميز بمرتفعاتها وتقاليدها الأصلية وهويتها الثقافية الفريدة.',
    'capital' => 'La Paz',
    'continent' => 'South America',
    'display_order' => 8,
    'is_active' => true,
],
[
    'name' => 'Paraguay',
    'ar_name' => 'باراغواي',
    'flag' => 'assets/flags/py.svg',
    'country_code' => 'PY',
    'currency_code' => 'PYG',
    'phone_code' => '+595',
    'description' => 'Paraguay is a landlocked nation with strong traditions, warm communities and cultural heritage.',
    'ar_description' => 'باراغواي دولة داخلية تتميز بتقاليد قوية ومجتمعات دافئة وتراث ثقافي.',
    'capital' => 'Asunción',
    'continent' => 'South America',
    'display_order' => 9,
    'is_active' => true,
],
[
    'name' => 'Venezuela',
    'ar_name' => 'فنزويلا',
    'flag' => 'assets/flags/ve.svg',
    'country_code' => 'VE',
    'currency_code' => 'VES',
    'phone_code' => '+58',
    'description' => 'Venezuela offers Caribbean beaches, mountains and vibrant artistic and cultural traditions.',
    'ar_description' => 'فنزويلا تتميز بشواطئ كاريبية وجبال وتقاليد فنية وثقافية نابضة.',
    'capital' => 'Caracas',
    'continent' => 'South America',
    'display_order' => 10,
    'is_active' => true,
],
[
    'name' => 'Australia',
    'ar_name' => 'أستراليا',
    'flag' => 'assets/flags/au.svg',
    'country_code' => 'AU',
    'currency_code' => 'AUD',
    'phone_code' => '+61',
    'description' => 'Australia is a modern and diverse nation known for high living standards, strong universities and beautiful landscapes.',
    'ar_description' => 'أستراليا دولة حديثة ومتنوعة تشتهر بمستوى المعيشة العالي وجامعات قوية ومناظر طبيعية خلابة.',
    'capital' => 'Canberra',
    'continent' => 'Oceania',
    'display_order' => 1,
    'is_active' => true,
],
[
    'name' => 'New Zealand',
    'ar_name' => 'نيوزيلندا',
    'flag' => 'assets/flags/nz.svg',
    'country_code' => 'NZ',
    'currency_code' => 'NZD',
    'phone_code' => '+64',
    'description' => 'New Zealand is known for its stunning nature, friendly communities and highly respected education system.',
    'ar_description' => 'نيوزيلندا مشهورة بطبيعتها الخلابة ومجتمعاتها الودودة ونظامها التعليمي المرموق.',
    'capital' => 'Wellington',
    'continent' => 'Oceania',
    'display_order' => 2,
    'is_active' => true,
],
[
    'name' => 'Fiji',
    'ar_name' => 'فيجي',
    'flag' => 'assets/flags/fj.svg',
    'country_code' => 'FJ',
    'currency_code' => 'FJD',
    'phone_code' => '+679',
    'description' => 'Fiji is a tropical island nation known for its beaches, warm hospitality and unique cultural heritage.',
    'ar_description' => 'فيجي دولة جزرية استوائية تشتهر بشواطئها وضيافتها الدافئة وتراثها الثقافي الفريد.',
    'capital' => 'Suva',
    'continent' => 'Oceania',
    'display_order' => 3,
    'is_active' => true,
],
[
    'name' => 'Papua New Guinea',
    'ar_name' => 'بابوا غينيا الجديدة',
    'flag' => 'assets/flags/pg.svg',
    'country_code' => 'PG',
    'currency_code' => 'PGK',
    'phone_code' => '+675',
    'description' => 'Papua New Guinea offers cultural diversity, traditional communities and distinctive landscapes.',
    'ar_description' => 'بابوا غينيا الجديدة تتميز بتنوعها الثقافي ومجتمعاتها التقليدية ومناظرها الطبيعية المميزة.',
    'capital' => 'Port Moresby',
    'continent' => 'Oceania',
    'display_order' => 4,
    'is_active' => true,
],
[
    'name' => 'Samoa',
    'ar_name' => 'ساموا',
    'flag' => 'assets/flags/ws.svg',
    'country_code' => 'WS',
    'currency_code' => 'WST',
    'phone_code' => '+685',
    'description' => 'Samoa is a peaceful island country with strong traditions, natural beauty and welcoming communities.',
    'ar_description' => 'ساموا دولة جزرية مسالمة تتميز بتقاليد قوية وجمال طبيعي ومجتمعات مضيافة.',
    'capital' => 'Apia',
    'continent' => 'Oceania',
    'display_order' => 5,
    'is_active' => true,
],
[
    'name' => 'Tonga',
    'ar_name' => 'تونغا',
    'flag' => 'assets/flags/to.svg',
    'country_code' => 'TO',
    'currency_code' => 'TOP',
    'phone_code' => '+676',
    'description' => 'Tonga is a Pacific island kingdom known for its cultural history, friendly people and relaxing environment.',
    'ar_description' => 'تونغا مملكة جزرية في المحيط الهادئ تشتهر بتاريخها الثقافي وشعبها الودود وبيئتها الهادئة.',
    'capital' => 'Nukuʻalofa',
    'continent' => 'Oceania',
    'display_order' => 6,
    'is_active' => true,
],
[
    'name' => 'Vanuatu',
    'ar_name' => 'فانواتو',
    'flag' => 'assets/flags/vu.svg',
    'country_code' => 'VU',
    'currency_code' => 'VUV',
    'phone_code' => '+678',
    'description' => 'Vanuatu features tropical islands, volcanic landscapes and traditional cultures across its regions.',
    'ar_description' => 'فانواتو تضم جزر استوائية ومناظر بركانية وثقافات تقليدية متنوعة.',
    'capital' => 'Port Vila',
    'continent' => 'Oceania',
    'display_order' => 7,
    'is_active' => true,
],
[
    'name' => 'Kiribati',
    'ar_name' => 'كيريباتي',
    'flag' => 'assets/flags/ki.svg',
    'country_code' => 'KI',
    'currency_code' => 'AUD',
    'phone_code' => '+686',
    'description' => 'Kiribati is a remote island nation known for its unique geography and traditional Pacific lifestyle.',
    'ar_description' => 'كيريباتي دولة جزرية نائية تشتهر بجغرافيتها الفريدة ونمط الحياة الباسيفيكي التقليدي.',
    'capital' => 'South Tarawa',
    'continent' => 'Oceania',
    'display_order' => 8,
    'is_active' => true,
],
[
    'name' => 'Solomon Islands',
    'ar_name' => 'جزر سليمان',
    'flag' => 'assets/flags/sb.svg',
    'country_code' => 'SB',
    'currency_code' => 'SBD',
    'phone_code' => '+677',
    'description' => 'The Solomon Islands offer natural beauty, marine life and diverse cultural groups.',
    'ar_description' => 'جزر سليمان تتميز بجمالها الطبيعي وحياتها البحرية وتنوع مجموعاتها الثقافية.',
    'capital' => 'Honiara',
    'continent' => 'Oceania',
    'display_order' => 9,
    'is_active' => true,
],
[
    'name' => 'Marshall Islands',
    'ar_name' => 'جزر مارشال',
    'flag' => 'assets/flags/mh.svg',
    'country_code' => 'MH',
    'currency_code' => 'USD',
    'phone_code' => '+692',
    'description' => 'The Marshall Islands is a Pacific nation known for its coral atolls, marine life and peaceful lifestyle.',
    'ar_description' => 'جزر مارشال دولة في المحيط الهادئ تشتهر بجزرها المرجانية وحياتها البحرية ونمطها الهادئ.',
    'capital' => 'Majuro',
    'continent' => 'Oceania',
    'display_order' => 10,
    'is_active' => true,
],
// MENA region - all Arabic countries (no duplicates with previous lists)
[
    'name' => 'Saudi Arabia',
    'ar_name' => 'المملكة العربية السعودية',
    'flag' => 'assets/flags/sa.svg',
    'country_code' => 'SA',
    'currency_code' => 'SAR',
    'phone_code' => '+966',
    'description' => 'Saudi Arabia is a key country in the Middle East known for its economic strength, religious significance and modern cities.',
    'ar_description' => 'المملكة العربية السعودية دولة محورية في الشرق الأوسط تشتهر بقوتها الاقتصادية وأهميتها الدينية ومدنها الحديثة.',
    'capital' => 'Riyadh',
    'continent' => 'Asia',
    'display_order' => 1,
    'is_active' => true,
],
[
    'name' => 'United Arab Emirates',
    'ar_name' => 'الإمارات العربية المتحدة',
    'flag' => 'assets/flags/ae.svg',
    'country_code' => 'AE',
    'currency_code' => 'AED',
    'phone_code' => '+971',
    'description' => 'The United Arab Emirates has rapidly developed into a regional hub for business, tourism, innovation and higher education.',
    'ar_description' => 'الإمارات العربية المتحدة تطورت بسرعة لتصبح مركزاً إقليمياً للأعمال والسياحة والابتكار والتعليم العالي.',
    'capital' => 'Abu Dhabi',
    'continent' => 'Asia',
    'display_order' => 2,
    'is_active' => true,
],
[
    'name' => 'Qatar',
    'ar_name' => 'قطر',
    'flag' => 'assets/flags/qa.svg',
    'country_code' => 'QA',
    'currency_code' => 'QAR',
    'phone_code' => '+974',
    'description' => 'Qatar is a small but influential Gulf state known for its modern infrastructure, education city and international events.',
    'ar_description' => 'قطر دولة خليجية صغيرة لكنها مؤثرة تشتهر ببنيتها التحتية الحديثة ومدينة التعليم واستضافة الفعاليات الدولية.',
    'capital' => 'Doha',
    'continent' => 'Asia',
    'display_order' => 3,
    'is_active' => true,
],
[
    'name' => 'Kuwait',
    'ar_name' => 'الكويت',
    'flag' => 'assets/flags/kw.svg',
    'country_code' => 'KW',
    'currency_code' => 'KWD',
    'phone_code' => '+965',
    'description' => 'Kuwait is a Gulf country with a strong oil-based economy, modern services and an active cultural life.',
    'ar_description' => 'الكويت دولة خليجية ذات اقتصاد قوي يعتمد على النفط وخدمات حديثة وحياة ثقافية نشطة.',
    'capital' => 'Kuwait City',
    'continent' => 'Asia',
    'display_order' => 4,
    'is_active' => true,
],
[
    'name' => 'Bahrain',
    'ar_name' => 'البحرين',
    'flag' => 'assets/flags/bh.svg',
    'country_code' => 'BH',
    'currency_code' => 'BHD',
    'phone_code' => '+973',
    'description' => 'Bahrain is an island kingdom in the Gulf known for its financial sector, cultural heritage and welcoming atmosphere.',
    'ar_description' => 'البحرين مملكة جزيرية في الخليج تشتهر بقطاعها المالي وتراثها الثقافي وبيئتها المضيافة.',
    'capital' => 'Manama',
    'continent' => 'Asia',
    'display_order' => 5,
    'is_active' => true,
],
[
    'name' => 'Oman',
    'ar_name' => 'عُمان',
    'flag' => 'assets/flags/om.svg',
    'country_code' => 'OM',
    'currency_code' => 'OMR',
    'phone_code' => '+968',
    'description' => 'Oman combines rich history, coastal cities and mountains, offering a calm lifestyle and growing education options.',
    'ar_description' => 'عُمان دولة تجمع بين تاريخ عريق ومدن ساحلية وجبال، وتوفر نمط حياة هادئاً وخيارات تعليمية متنامية.',
    'capital' => 'Muscat',
    'continent' => 'Asia',
    'display_order' => 6,
    'is_active' => true,
],
[
    'name' => 'Yemen',
    'ar_name' => 'اليمن',
    'flag' => 'assets/flags/ye.svg',
    'country_code' => 'YE',
    'currency_code' => 'YER',
    'phone_code' => '+967',
    'description' => 'Yemen is a historic country on the Arabian Peninsula known for its traditional architecture and cultural heritage.',
    'ar_description' => 'اليمن دولة تاريخية في شبه الجزيرة العربية تشتهر بعمارتها التقليدية وتراثها الثقافي العريق.',
    'capital' => 'Sana\'a',
    'continent' => 'Asia',
    'display_order' => 7,
    'is_active' => true,
],
[
    'name' => 'Jordan',
    'ar_name' => 'الأردن',
    'flag' => 'assets/flags/jo.svg',
    'country_code' => 'JO',
    'currency_code' => 'JOD',
    'phone_code' => '+962',
    'description' => 'Jordan is a stable Middle Eastern country known for Petra, the Dead Sea, and reputable universities and schools.',
    'ar_description' => 'الأردن دولة مستقرة في الشرق الأوسط تشتهر بمدينة البتراء والبحر الميت وجامعات ومدارس ذات سمعة جيدة.',
    'capital' => 'Amman',
    'continent' => 'Asia',
    'display_order' => 8,
    'is_active' => true,
],
[
    'name' => 'Lebanon',
    'ar_name' => 'لبنان',
    'flag' => 'assets/flags/lb.svg',
    'country_code' => 'LB',
    'currency_code' => 'LBP',
    'phone_code' => '+961',
    'description' => 'Lebanon is a Mediterranean country with a long history, rich culture and strong tradition in education and services.',
    'ar_description' => 'لبنان دولة متوسطية ذات تاريخ طويل وثقافة غنية وتقاليد قوية في مجالات التعليم والخدمات.',
    'capital' => 'Beirut',
    'continent' => 'Asia',
    'display_order' => 9,
    'is_active' => true,
],
[
    'name' => 'Syria',
    'ar_name' => 'سوريا',
    'flag' => 'assets/flags/sy.svg',
    'country_code' => 'SY',
    'currency_code' => 'SYP',
    'phone_code' => '+963',
    'description' => 'Syria is a historic country in the Levant region known for its ancient cities, culture and traditional markets.',
    'ar_description' => 'سوريا دولة تاريخية في منطقة الشام تشتهر بمدنها القديمة وثقافتها وأسواقها التقليدية.',
    'capital' => 'Damascus',
    'continent' => 'Asia',
    'display_order' => 10,
    'is_active' => true,
],
[
    'name' => 'Iraq',
    'ar_name' => 'العراق',
    'flag' => 'assets/flags/iq.svg',
    'country_code' => 'IQ',
    'currency_code' => 'IQD',
    'phone_code' => '+964',
    'description' => 'Iraq is home to ancient Mesopotamian civilizations and remains an important cultural and historical center.',
    'ar_description' => 'العراق موطن لحضارات بلاد الرافدين القديمة ولا يزال مركزاً ثقافياً وتاريخياً مهماً في المنطقة.',
    'capital' => 'Baghdad',
    'continent' => 'Asia',
    'display_order' => 11,
    'is_active' => true,
],
[
    'name' => 'Palestine',
    'ar_name' => 'فلسطين',
    'flag' => 'assets/flags/ps.svg',
    'country_code' => 'PS',
    'currency_code' => 'ILS',
    'phone_code' => '+970',
    'description' => 'Palestine is a historic land in the Levant region known for its cultural identity and religious significance.',
    'ar_description' => 'فلسطين أرض تاريخية في منطقة الشام تشتهر بهويتها الثقافية وأهميتها الدينية.',
    'capital' => 'Ramallah',
    'continent' => 'Asia',
    'display_order' => 12,
    'is_active' => true,
],
[
    'name' => 'Libya',
    'ar_name' => 'ليبيا',
    'flag' => 'assets/flags/ly.svg',
    'country_code' => 'LY',
    'currency_code' => 'LYD',
    'phone_code' => '+218',
    'description' => 'Libya is a North African country with Mediterranean coastline, desert interiors and rich cultural traditions.',
    'ar_description' => 'ليبيا دولة في شمال أفريقيا ذات سواحل متوسطية وصحارى داخلية وتراث ثقافي متنوع.',
    'capital' => 'Tripoli',
    'continent' => 'Africa',
    'display_order' => 13,
    'is_active' => true,
],
[
    'name' => 'Sudan',
    'ar_name' => 'السودان',
    'flag' => 'assets/flags/sd.svg',
    'country_code' => 'SD',
    'currency_code' => 'SDG',
    'phone_code' => '+249',
    'description' => 'Sudan is a large African country along the Nile River with diverse cultures and long historical roots.',
    'ar_description' => 'السودان دولة إفريقية كبيرة على نهر النيل تتميز بتنوع ثقافي وجذور تاريخية عميقة.',
    'capital' => 'Khartoum',
    'continent' => 'Africa',
    'display_order' => 14,
    'is_active' => true,
],
[
    'name' => 'Mauritania',
    'ar_name' => 'موريتانيا',
    'flag' => 'assets/flags/mr.svg',
    'country_code' => 'MR',
    'currency_code' => 'MRU',
    'phone_code' => '+222',
    'description' => 'Mauritania is a West African Arab country with desert landscapes, Atlantic coastline and traditional culture.',
    'ar_description' => 'موريتانيا دولة عربية في غرب أفريقيا تتميز بصحاري واسعة وسواحل أطلسية وثقافة تقليدية.',
    'capital' => 'Nouakchott',
    'continent' => 'Africa',
    'display_order' => 15,
    'is_active' => true,
],
[
    'name' => 'Comoros',
    'ar_name' => 'جزر القمر',
    'flag' => 'assets/flags/km.svg',
    'country_code' => 'KM',
    'currency_code' => 'KMF',
    'phone_code' => '+269',
    'description' => 'The Comoros is an island nation in the Indian Ocean with Arabic influences, tropical climate and marine life.',
    'ar_description' => 'جزر القمر دولة جزرية في المحيط الهندي ذات تأثيرات عربية ومناخ استوائي وحياة بحرية غنية.',
    'capital' => 'Moroni',
    'continent' => 'Africa',
    'display_order' => 16,
    'is_active' => true,
],
[
    'name' => 'Djibouti',
    'ar_name' => 'جيبوتي',
    'flag' => 'assets/flags/dj.svg',
    'country_code' => 'DJ',
    'currency_code' => 'DJF',
    'phone_code' => '+253',
    'description' => 'Djibouti is a small strategic country on the Red Sea known for its ports and multilingual society.',
    'ar_description' => 'جيبوتي دولة صغيرة ذات موقع استراتيجي على البحر الأحمر تشتهر بموانئها ومجتمعها متعدّد اللغات.',
    'capital' => 'Djibouti',
    'continent' => 'Africa',
    'display_order' => 17,
    'is_active' => true,
],
[
    'name' => 'Somalia',
    'ar_name' => 'الصومال',
    'flag' => 'assets/flags/so.svg',
    'country_code' => 'SO',
    'currency_code' => 'SOS',
    'phone_code' => '+252',
    'description' => 'Somalia lies on the Horn of Africa and is known for its long coastline, trading history and cultural traditions.',
    'ar_description' => 'الصومال تقع في القرن الأفريقي وتشتهر بسواحلها الطويلة وتاريخها التجاري وتقاليدها الثقافية.',
    'capital' => 'Mogadishu',
    'continent' => 'Africa',
    'display_order' => 18,
    'is_active' => true,
],

// 20 key countries of Asia (non-duplicate, including Bangladesh, India, Pakistan)
[
    'name' => 'India',
    'ar_name' => 'الهند',
    'flag' => 'assets/flags/in.svg',
    'country_code' => 'IN',
    'currency_code' => 'INR',
    'phone_code' => '+91',
    'description' => 'India is a vast South Asian country with diverse cultures, major cities and a strong higher education system.',
    'ar_description' => 'الهند دولة واسعة في جنوب آسيا تتميز بتنوع ثقافي كبير ومدن رئيسية ونظام تعليم عالٍ متطور.',
    'capital' => 'New Delhi',
    'continent' => 'Asia',
    'display_order' => 1,
    'is_active' => true,
],
[
    'name' => 'Bangladesh',
    'ar_name' => 'بنغلاديش',
    'flag' => 'assets/flags/bd.svg',
    'country_code' => 'BD',
    'currency_code' => 'BDT',
    'phone_code' => '+880',
    'description' => 'Bangladesh is a densely populated country with a growing economy, rich culture and expanding education sector.',
    'ar_description' => 'بنغلاديش دولة ذات كثافة سكانية عالية واقتصاد متنامٍ وثقافة غنية وقطاع تعليمي آخذ في التطور.',
    'capital' => 'Dhaka',
    'continent' => 'Asia',
    'display_order' => 2,
    'is_active' => true,
],
[
    'name' => 'Pakistan',
    'ar_name' => 'باكستان',
    'flag' => 'assets/flags/pk.svg',
    'country_code' => 'PK',
    'currency_code' => 'PKR',
    'phone_code' => '+92',
    'description' => 'Pakistan is a South Asian country with mountain ranges, historic cities and a large youth population.',
    'ar_description' => 'باكستان دولة في جنوب آسيا تتميز بسلاسل جبلية ومدن تاريخية ونسبة كبيرة من الشباب.',
    'capital' => 'Islamabad',
    'continent' => 'Asia',
    'display_order' => 3,
    'is_active' => true,
],
[
    'name' => 'China',
    'ar_name' => 'الصين',
    'flag' => 'assets/flags/cn.svg',
    'country_code' => 'CN',
    'currency_code' => 'CNY',
    'phone_code' => '+86',
    'description' => 'China is one of the world’s largest countries, known for rapid development, ancient history and major universities.',
    'ar_description' => 'الصين من أكبر دول العالم وتشهد تطوراً سريعاً، وتشتهر بتاريخ عريق وجامعات كبرى معترف بها.',
    'capital' => 'Beijing',
    'continent' => 'Asia',
    'display_order' => 4,
    'is_active' => true,
],
[
    'name' => 'Japan',
    'ar_name' => 'اليابان',
    'flag' => 'assets/flags/jp.svg',
    'country_code' => 'JP',
    'currency_code' => 'JPY',
    'phone_code' => '+81',
    'description' => 'Japan is a highly developed island nation known for technology, safety, efficient transport and quality education.',
    'ar_description' => 'اليابان دولة جزرية متقدمة للغاية تشتهر بالتكنولوجيا والأمان والمواصلات الفعالة والتعليم عالي الجودة.',
    'capital' => 'Tokyo',
    'continent' => 'Asia',
    'display_order' => 5,
    'is_active' => true,
],
[
    'name' => 'South Korea',
    'ar_name' => 'كوريا الجنوبية',
    'flag' => 'assets/flags/kr.svg',
    'country_code' => 'KR',
    'currency_code' => 'KRW',
    'phone_code' => '+82',
    'description' => 'South Korea is known for advanced technology, popular culture and competitive universities in major cities.',
    'ar_description' => 'كوريا الجنوبية دولة معروفة بالتكنولوجيا المتقدمة والثقافة الشعبية والجامعات التنافسية في مدنها الكبرى.',
    'capital' => 'Seoul',
    'continent' => 'Asia',
    'display_order' => 6,
    'is_active' => true,
],
[
    'name' => 'Indonesia',
    'ar_name' => 'إندونيسيا',
    'flag' => 'assets/flags/id.svg',
    'country_code' => 'ID',
    'currency_code' => 'IDR',
    'phone_code' => '+62',
    'description' => 'Indonesia is a large archipelago nation with many islands, diverse cultures and growing urban centers.',
    'ar_description' => 'إندونيسيا دولة أرخبيل كبيرة تضم العديد من الجزر وثقافات متنوعة ومراكز حضرية متنامية.',
    'capital' => 'Jakarta',
    'continent' => 'Asia',
    'display_order' => 7,
    'is_active' => true,
],
[
    'name' => 'Malaysia',
    'ar_name' => 'ماليزيا',
    'flag' => 'assets/flags/my.svg',
    'country_code' => 'MY',
    'currency_code' => 'MYR',
    'phone_code' => '+60',
    'description' => 'Malaysia is a multicultural country known for modern cities, tropical nature and popular study destinations.',
    'ar_description' => 'ماليزيا دولة متعددة الثقافات تشتهر بمدنها الحديثة وطبيعتها الاستوائية وكونها وجهة مفضلة للدراسة.',
    'capital' => 'Kuala Lumpur',
    'continent' => 'Asia',
    'display_order' => 8,
    'is_active' => true,
],
[
    'name' => 'Singapore',
    'ar_name' => 'سنغافورة',
    'flag' => 'assets/flags/sg.svg',
    'country_code' => 'SG',
    'currency_code' => 'SGD',
    'phone_code' => '+65',
    'description' => 'Singapore is a global city-state known for safety, efficiency, strong economy and world-class universities.',
    'ar_description' => 'سنغافورة مدينة-دولة عالمية تشتهر بالأمان والكفاءة والاقتصاد القوي والجامعات ذات التصنيف العالمي.',
    'capital' => 'Singapore',
    'continent' => 'Asia',
    'display_order' => 9,
    'is_active' => true,
],
[
    'name' => 'Thailand',
    'ar_name' => 'تايلاند',
    'flag' => 'assets/flags/th.svg',
    'country_code' => 'TH',
    'currency_code' => 'THB',
    'phone_code' => '+66',
    'description' => 'Thailand is a Southeast Asian country famous for tourism, friendly people and vibrant city life.',
    'ar_description' => 'تايلاند دولة في جنوب شرق آسيا تشتهر بالسياحة وشعبها الودود وحياة المدن النابضة بالحياة.',
    'capital' => 'Bangkok',
    'continent' => 'Asia',
    'display_order' => 10,
    'is_active' => true,
],
[
    'name' => 'Vietnam',
    'ar_name' => 'فيتنام',
    'flag' => 'assets/flags/vn.svg',
    'country_code' => 'VN',
    'currency_code' => 'VND',
    'phone_code' => '+84',
    'description' => 'Vietnam combines historic towns, coastal areas and mountains, with a rapidly growing modern economy.',
    'ar_description' => 'فيتنام تجمع بين مدن تاريخية ومناطق ساحلية وجبال مع اقتصاد حديث ينمو بسرعة.',
    'capital' => 'Hanoi',
    'continent' => 'Asia',
    'display_order' => 11,
    'is_active' => true,
],
[
    'name' => 'Philippines',
    'ar_name' => 'الفلبين',
    'flag' => 'assets/flags/ph.svg',
    'country_code' => 'PH',
    'currency_code' => 'PHP',
    'phone_code' => '+63',
    'description' => 'The Philippines is an island nation known for English-based education, tropical climate and friendly communities.',
    'ar_description' => 'الفلبين دولة جزرية تشتهر بالتعليم القائم على اللغة الإنجليزية والمناخ الاستوائي والمجتمعات الودودة.',
    'capital' => 'Manila',
    'continent' => 'Asia',
    'display_order' => 12,
    'is_active' => true,
],
[
    'name' => 'Sri Lanka',
    'ar_name' => 'سريلانكا',
    'flag' => 'assets/flags/lk.svg',
    'country_code' => 'LK',
    'currency_code' => 'LKR',
    'phone_code' => '+94',
    'description' => 'Sri Lanka is an island country in the Indian Ocean with tea plantations, beaches and cultural heritage.',
    'ar_description' => 'سريلانكا دولة جزرية في المحيط الهندي تشتهر بمزارع الشاي وشواطئها وتراثها الثقافي.',
    'capital' => 'Sri Jayawardenepura Kotte',
    'continent' => 'Asia',
    'display_order' => 13,
    'is_active' => true,
],
[
    'name' => 'Nepal',
    'ar_name' => 'نيبال',
    'flag' => 'assets/flags/np.svg',
    'country_code' => 'NP',
    'currency_code' => 'NPR',
    'phone_code' => '+977',
    'description' => 'Nepal is a landlocked Himalayan country famous for high mountains, trekking routes and spiritual heritage.',
    'ar_description' => 'نيبال دولة حبيسة في جبال الهيمالايا تشتهر بقممها العالية ومسارات التسلق وتراثها الروحي.',
    'capital' => 'Kathmandu',
    'continent' => 'Asia',
    'display_order' => 14,
    'is_active' => true,
],
[
    'name' => 'Maldives',
    'ar_name' => 'جزر المالديف',
    'flag' => 'assets/flags/mv.svg',
    'country_code' => 'MV',
    'currency_code' => 'MVR',
    'phone_code' => '+960',
    'description' => 'The Maldives is a tropical island nation known for luxury resorts, clear waters and peaceful lifestyle.',
    'ar_description' => 'جزر المالديف دولة جزرية استوائية تشتهر بالمنتجعات الفاخرة والمياه الصافية ونمط الحياة الهادئ.',
    'capital' => 'Malé',
    'continent' => 'Asia',
    'display_order' => 15,
    'is_active' => true,
],
[
    'name' => 'Turkey',
    'ar_name' => 'تركيا',
    'flag' => 'assets/flags/tr.svg',
    'country_code' => 'TR',
    'currency_code' => 'TRY',
    'phone_code' => '+90',
    'description' => 'Turkey bridges Europe and Asia and is known for historic cities, coastal regions and growing universities.',
    'ar_description' => 'تركيا دولة تربط بين أوروبا وآسيا وتشتهر بمدنها التاريخية ومناطقها الساحلية وجامعاتها المتنامية.',
    'capital' => 'Ankara',
    'continent' => 'Asia',
    'display_order' => 16,
    'is_active' => true,
],
[
    'name' => 'Azerbaijan',
    'ar_name' => 'أذربيجان',
    'flag' => 'assets/flags/az.svg',
    'country_code' => 'AZ',
    'currency_code' => 'AZN',
    'phone_code' => '+994',
    'description' => 'Azerbaijan is a Caucasus country with modern development, energy resources and historic sites.',
    'ar_description' => 'أذربيجان دولة في منطقة القوقاز تجمع بين التنمية الحديثة والموارد الطاقة والمواقع التاريخية.',
    'capital' => 'Baku',
    'continent' => 'Asia',
    'display_order' => 17,
    'is_active' => true,
],
[
    'name' => 'Kazakhstan',
    'ar_name' => 'كازاخستان',
    'flag' => 'assets/flags/kz.svg',
    'country_code' => 'KZ',
    'currency_code' => 'KZT',
    'phone_code' => '+7',
    'description' => 'Kazakhstan is a large Central Asian country with steppe landscapes, modern cities and growing universities.',
    'ar_description' => 'كازاخستان دولة كبيرة في آسيا الوسطى تتميز بسهول واسعة ومدن حديثة وجامعات في تطور مستمر.',
    'capital' => 'Astana',
    'continent' => 'Asia',
    'display_order' => 18,
    'is_active' => true,
],
[
    'name' => 'Iran',
    'ar_name' => 'إيران',
    'flag' => 'assets/flags/ir.svg',
    'country_code' => 'IR',
    'currency_code' => 'IRR',
    'phone_code' => '+98',
    'description' => 'Iran is a large country with ancient Persian history, diverse climates and strong cultural traditions.',
    'ar_description' => 'إيران دولة كبيرة ذات تاريخ فارسي عريق ومناخات متنوعة وتقاليد ثقافية راسخة.',
    'capital' => 'Tehran',
    'continent' => 'Asia',
    'display_order' => 19,
    'is_active' => true,
],
[
    'name' => 'Afghanistan',
    'ar_name' => 'أفغانستان',
    'flag' => 'assets/flags/af.svg',
    'country_code' => 'AF',
    'currency_code' => 'AFN',
    'phone_code' => '+93',
    'description' => 'Afghanistan is a landlocked country in Central and South Asia with mountainous terrain and long history.',
    'ar_description' => 'أفغانستان دولة حبيسة في آسيا الوسطى والجنوبية تتميز بتضاريس جبلية وتاريخ طويل ومعقد.',
    'capital' => 'Kabul',
    'continent' => 'Asia',
    'display_order' => 20,
    'is_active' => true,
],


        ];

        $countries = array_values(array_map(function ($country, $index) {
            $country['display_order'] = $index + 1;
            return $country;
        }, $countries, array_keys($countries)));

        DB::table('countries')->insert($countries);
    }
}
