<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SchoolSeeder extends Seeder
{
    public function run(): void
    {
        $schools = [
    [
        'name' => 'IH International House',
        'ar_name' => 'معهد إنترناشونال هاوس',
        'slug' => 'IH International House',
        'description' => 'IH International House is a well-known English language school that welcomes students from many countries. The school focuses on practical communication skills, small class sizes and supportive teachers to help learners build confidence in real-life situations.',
        'ar_description' => 'يُعد معهد إنترناشونال هاوس من المعاهد المعروفة لتعليم اللغة الإنجليزية ويستقبل طلاباً من دول عديدة. يركز المعهد على مهارات التواصل العملية، وحصص صغيرة، ومدرسين داعمين لمساعدة المتعلمين على اكتساب الثقة في مواقف الحياة اليومية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'The Bournemouth School of English',
        'ar_name' => 'مدرسة بورنموث للغة الإنجليزية',
        'slug' => 'The Bournemouth School of English',
        'description' => 'The Bournemouth School of English offers high-quality English courses in the seaside town of Bournemouth. Students study in a friendly environment with experienced teachers, modern classrooms and a focus on speaking, listening, reading and writing skills.',
        'ar_description' => 'تقدّم مدرسة بورنموث للغة الإنجليزية دورات عالية الجودة في مدينة بورنموث الساحلية. يدرس الطلاب في بيئة ودّية مع مدرسين ذوي خبرة وفصول حديثة مع تركيز على مهارات التحدث والاستماع والقراءة والكتابة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 4]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Anglotec Academy',
        'ar_name' => 'أكاديمية أنغلوتك',
        'slug' => 'Anglotec Academy',
        'description' => 'Anglotec Academy is a small and welcoming English language school that provides personalised attention to each learner. The academy focuses on real communication, cultural activities and helping students achieve their study or work goals.',
        'ar_description' => 'أكاديمية أنغلوتك هي مدرسة لغة إنجليزية صغيرة ومرحِّبة توفّر اهتماماً فردياً لكل متعلم. تركز الأكاديمية على التواصل الحقيقي والأنشطة الثقافية ومساعدة الطلاب على تحقيق أهدافهم الدراسية أو المهنية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Atlantic Centre of Education',
        'ar_name' => 'مركز أتلانتيك للتعليم',
        'slug' => 'Atlantic Centre of Education',
        'description' => 'Atlantic Centre of Education in Ireland combines English language learning with cultural experiences. Students enjoy a supportive atmosphere, social activities and professional teaching that helps them improve quickly and feel at home during their stay.',
        'ar_description' => 'يجمع مركز أتلانتيك للتعليم في أيرلندا بين تعلم اللغة الإنجليزية والتعرّف على الثقافة المحلية. يستمتع الطلاب بأجواء داعمة وأنشطة اجتماعية وتدريس مهني يساعدهم على التطور السريع والشعور كأنهم في وطنهم أثناء الإقامة.',
        'logo' => null,
        'accreditation_ids' => json_encode([17, 16, 7]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Bath Academy of English',
        'ar_name' => 'معهد أكاديمية باث',
        'slug' => 'Bath Academy of English',
        'description' => 'Bath Academy of English is an independent college in the historic city of Bath. It offers English language and academic preparation courses in a caring environment, with close support from teachers and small groups that help students focus on progress.',
        'ar_description' => 'معهد أكاديمية باث هو كلية مستقلة في مدينة باث التاريخية. يقدم دورات لغة إنجليزية وبرامج إعداد أكاديمي في بيئة تهتم بالطالب، مع دعم مباشر من المدرسين ومجموعات صغيرة تساعد على التركيز على التقدم.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 5, 6]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Bayswater',
        'ar_name' => 'معهد بيزووتر',
        'slug' => 'Bayswater',
        'description' => 'Bayswater is a modern network of language schools in several international cities. The school offers English courses for adults and young learners, combining classroom lessons with digital resources, social activities and career-focused programmes.',
        'ar_description' => 'معهد بيزووتر شبكة حديثة من معاهد اللغة في عدة مدن حول العالم. يقدّم المعهد دورات في اللغة الإنجليزية للكبار واليافعين، مع دمج الدروس الصفية بالموارد الرقمية والأنشطة الاجتماعية والبرامج الموجهة للحياة المهنية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 10]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Beet Language Centre',
        'ar_name' => 'معهد بيت لانقويج سنتر',
        'slug' => 'Beet Language Centre',
        'description' => 'Beet Language Centre in Bournemouth is a family-run school with a long history of teaching English. The centre provides general English, exam preparation and teacher training, with a friendly atmosphere and a strong reputation for quality.',
        'ar_description' => 'معهد بيت لانقويج سنتر في بورنموث هو معهد عائلي ذو خبرة طويلة في تدريس اللغة الإنجليزية. يقدم المعهد دورات عامة، ودورات تحضير للامتحانات، وبرامج لتدريب المعلمين في جو ودود وسمعة قوية من حيث الجودة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 8, 18, 4, 9, 21]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Berlitz',
        'ar_name' => 'معهد بيرلتز',
        'slug' => 'Berlitz',
        'description' => 'Berlitz is part of an international chain of language centres known for its communicative teaching method. Students can choose flexible schedules and practical courses that focus on speaking confidence for study, travel or work.',
        'ar_description' => 'معهد بيرلتز جزء من سلسلة عالمية من مراكز اللغات معروفة بأسلوبها التواصلي في التدريس. يمكن للطلاب اختيار جداول مرنة ودورات عملية تركّز على تنمية الثقة في التحدث لأغراض الدراسة أو السفر أو العمل.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Bournemouth City College BCC',
        'ar_name' => 'كلية مدينة بورنموث BCC',
        'slug' => 'Bournemouth City College BCC',
        'description' => 'Bournemouth City College BCC offers English language and further education programmes in the coastal town of Bournemouth. The college provides a supportive environment where students can learn English and gain skills for future study or careers.',
        'ar_description' => 'تقدّم كلية مدينة بورنموث BCC برامج في اللغة الإنجليزية والتعليم الإضافي في مدينة بورنموث الساحلية. توفّر الكلية بيئة داعمة يمكن للطلاب من خلالها تعلم اللغة الإنجليزية واكتساب مهارات تفيدهم في الدراسة أو العمل مستقبلاً.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Bright School of English',
        'ar_name' => 'مدرسة برايت للغة الإنجليزية',
        'slug' => 'Bright School of English',
        'description' => 'Bright School of English in Bournemouth focuses on friendly, student-centred teaching. The school offers general English, conversation and exam courses, with small classes and personal support for each learner.',
        'ar_description' => 'مدرسة برايت للغة الإنجليزية في بورنموث تركّز على التدريس الذي يتمحور حول الطالب في أجواء ودودة. تقدّم المدرسة دورات إنجليزية عامة ودورات محادثة وتحضير للامتحانات مع فصول صغيرة ودعم فردي لكل متعلم.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Brighton Language College International',
        'ar_name' => 'معهد برايتون العالمي للغات',
        'slug' => 'Brighton Language College International',
        'description' => 'Brighton Language College International is located close to the seafront in Brighton. The college welcomes adult and junior students and offers a wide choice of English programmes, including summer schools and exam preparation.',
        'ar_description' => 'يقع معهد برايتون العالمي للغات بالقرب من الواجهة البحرية في مدينة برايتون. يستقبل المعهد طلاباً كباراً وصغاراً ويقدّم مجموعة واسعة من برامج اللغة الإنجليزية، بما في ذلك المدارس الصيفية ودورات تحضير الامتحانات.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 5, 4]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Britannia English Academy',
        'ar_name' => 'معهد بريتانيا إنجلش أكاديمي',
        'slug' => 'Britannia English Academy',
        'description' => 'Britannia English Academy in Manchester provides flexible English courses for adults. Students can study in the morning, afternoon or evening, and enjoy a friendly atmosphere that encourages communication and real practice.',
        'ar_description' => 'معهد بريتانيا إنجلش أكاديمي في مانشستر يقدم دورات مرنة في اللغة الإنجليزية للبالغين. يمكن للطلاب الدراسة صباحاً أو بعد الظهر أو مساءً والاستفادة من أجواء ودّية تشجع على التواصل والتطبيق العملي.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 4]),
        'rating' => 5.0,
    ],
    [
        'name' => 'BSC EDUCATION',
        'ar_name' => 'معهد بي إس سي التعليمي',
        'slug' => 'BSC EDUCATION',
        'description' => 'BSC EDUCATION operates English language centres in several popular study destinations. The schools offer general English, exam preparation and academic pathways, with modern facilities, digital resources and a strong focus on student progress.',
        'ar_description' => 'يدير معهد بي إس سي التعليمي عدداً من مراكز اللغة الإنجليزية في وجهات دراسية شهيرة. تقدم المدارس دورات عامة، ودورات تحضير للامتحانات، ومسارات أكاديمية مع مرافق حديثة وموارد رقمية وتركيز واضح على تقدم الطالب.',
        'logo' => null,
        'accreditation_ids' => json_encode([4, 3, 24, 2, 22, 23, 15, 28, 25, 26]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Burlington School',
        'ar_name' => 'معهد بيرلينغتون للغة الإنجليزية',
        'slug' => 'Burlington School',
        'description' => 'Burlington School is an English language school in London offering courses for adults and juniors. The school combines language lessons with accommodation and activities, helping students experience life in the UK.',
        'ar_description' => 'معهد بيرلينغتون للغة الإنجليزية هو معهد في لندن يقدم دورات للكبار واليافعين. يجمع المعهد بين دروس اللغة والسكن والأنشطة، مما يساعد الطلاب على تجربة الحياة في المملكة المتحدة بشكل متكامل.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Central Language School',
        'ar_name' => 'معهد سنترال للغات',
        'slug' => 'Central Language School',
        'description' => 'Central Language School in Cambridge offers English courses in a warm, Christian-inspired environment. Students benefit from small classes, personal attention and opportunities to explore the historic university city.',
        'ar_description' => 'يقع معهد سنترال للغات في مدينة كامبردج ويقدّم دورات في اللغة الإنجليزية في بيئة دافئة مستوحاة من القيم المسيحية. يستفيد الطلاب من الفصول الصغيرة والاهتمام الفردي وفرصة استكشاف المدينة الجامعية التاريخية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'CES - Centre of English Studies',
        'ar_name' => 'مركز دراسات اللغة الإنجليزية CES',
        'slug' => 'CES - Centre of English Studies',
        'description' => 'CES – Centre of English Studies has schools in the UK and Ireland. The London centre offers general English, exam preparation and young learner programmes with a friendly international atmosphere.',
        'ar_description' => 'يمتلك مركز دراسات اللغة الإنجليزية CES مدارس في المملكة المتحدة وأيرلندا. يقدم فرع لندن دورات إنجليزية عامة، ودورات تحضير للامتحانات، وبرامج لليافعين في أجواء دولية ودّية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 11]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Concorde International',
        'ar_name' => 'معهد كونكورد العالمي',
        'slug' => 'Concorde International',
        'description' => 'Concorde International in Canterbury specialises in English language and academic programmes. The school runs adult courses, junior vacation programmes and pathways for students who plan to continue their studies in the UK.',
        'ar_description' => 'معهد كونكورد العالمي في كانتربري متخصص في برامج اللغة الإنجليزية والبرامج الأكاديمية. يقدم المعهد دورات للكبار، وبرامج عطلات لليافعين، ومسارات للطلاب الذين يخططون لمواصلة الدراسة في المملكة المتحدة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 6, 5]),
        'rating' => 5.0,
    ],
    [
        'name' => 'ETC International College',
        'ar_name' => 'كلية إي تي سي الدولية',
        'slug' => 'ETC International College',
        'description' => 'ETC International College in Bournemouth offers a wide range of English courses and pathway programmes. Students study close to the beach and benefit from academic support, modern facilities and a mix of nationalities.',
        'ar_description' => 'كلية إي تي سي الدولية في بورنموث تقدّم مجموعة واسعة من دورات اللغة الإنجليزية وبرامج المسارات الأكاديمية. يدرس الطلاب بالقرب من الشاطئ ويستفيدون من دعم أكاديمي ومرافق حديثة وتنوع في الجنسيات.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Eurospeak Language School',
        'ar_name' => 'معهد يورو سبيك للغة الإنجليزية',
        'slug' => 'Eurospeak Language School',
        'description' => 'Eurospeak Language School has centres in Reading and Southampton. It offers affordable English courses for adults and young learners, with flexible timetables and a friendly, multicultural learning environment.',
        'ar_description' => 'يمتلك معهد يورو سبيك للغة الإنجليزية فروعاً في ريدنغ وساوثهامبتون. يقدّم المعهد دورات ميسورة التكلفة للغة الإنجليزية للكبار واليافعين مع جداول مرنة وبيئة تعلم متعددة الثقافات.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'ILC International Language Centres',
        'ar_name' => 'مراكز ILC الدولية للغات',
        'slug' => 'ILC International Language Centres',
        'description' => 'ILC International Language Centres operate in several UK cities, providing English language training for international students. The schools focus on communication, exam skills and helping learners adapt to life in the UK.',
        'ar_description' => 'تدير مراكز ILC الدولية للغات عدداً من الفروع في مدن بريطانية مختلفة لتقديم تدريب في اللغة الإنجليزية للطلاب الدوليين. تركز المدارس على التواصل ومهارات الامتحانات ومساعدة المتعلمين على التكيف مع الحياة في المملكة المتحدة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Imagine English Liverpool Academy',
        'ar_name' => 'أكاديمية إماجن إنجلش ليفربول',
        'slug' => 'Imagine English Liverpool Academy',
        'description' => 'Imagine English Liverpool Academy is an independent school in the city of Liverpool. It offers personalised English courses in small groups, helping students improve quickly in a relaxed and supportive environment.',
        'ar_description' => 'أكاديمية إماجن إنجلش ليفربول هي مدرسة مستقلة في مدينة ليفربول. تقدّم دورات مخصّصة في اللغة الإنجليزية ضمن مجموعات صغيرة، مما يساعد الطلاب على التطور السريع في بيئة مريحة وداعمة.',
        'logo' => null,
        'accreditation_ids' => json_encode([12]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Inlingua',
        'ar_name' => 'إنلنغوا',
        'slug' => 'Inlingua',
        'description' => 'Inlingua Cheltenham is part of the worldwide Inlingua network. The school offers general English, exam preparation and business courses, using a practical method that encourages students to speak from the first day.',
        'ar_description' => 'إنلنغوا تشلتنهام جزء من شبكة إنلنغوا العالمية. يقدم المعهد دورات عامة في اللغة الإنجليزية ودورات تحضير للامتحانات ودورات للأعمال باستخدام أسلوب عملي يشجع الطلاب على التحدث من اليوم الأول.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Islington Centre for English',
        'ar_name' => 'مركز إزلنغتون للغة الإنجليزية',
        'slug' => 'Islington Centre for English',
        'description' => 'Islington Centre for English is located in central London and offers affordable English courses. Students benefit from flexible timetables, friendly staff and a convenient location close to many attractions.',
        'ar_description' => 'يقع مركز إزلنغتون للغة الإنجليزية في وسط لندن ويقدم دورات ميسورة التكلفة في اللغة الإنجليزية. يستفيد الطلاب من جداول مرنة وطاقم ودود وموقع مميز قريب من العديد من المعالم.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 5]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Kensington Academy of English',
        'ar_name' => 'أكاديمية كنسينغتون للغة الإنجليزية',
        'slug' => 'Kensington Academy of English',
        'description' => 'Kensington Academy of English is a long-established school in London. It offers a variety of English programmes, from general courses to exam preparation, with experienced teachers and international classes.',
        'ar_description' => 'أكاديمية كنسينغتون للغة الإنجليزية هي مدرسة عريقة في لندن. تقدم مجموعة متنوعة من برامج اللغة الإنجليزية من الدورات العامة إلى دورات التحضير للامتحانات، مع مدرسين ذوي خبرة وفصول دولية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Leeds Language College Ltd',
        'ar_name' => 'كلية ليدز للغة',
        'slug' => 'Leeds Language College Ltd',
        'description' => 'Leeds Language College Ltd is based in the vibrant city of Leeds. The college offers English courses for adults, including general English and exam classes, in a supportive and multicultural environment.',
        'ar_description' => 'تقع كلية ليدز للغة في مدينة ليدز الحيوية. تقدم الكلية دورات في اللغة الإنجليزية للبالغين، بما في ذلك الدورات العامة ودورات الامتحانات، ضمن بيئة داعمة ومتعددة الثقافات.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Lewis School of English',
        'ar_name' => 'مدرسة لويس للغة الإنجليزية',
        'slug' => 'Lewis School of English',
        'description' => 'Lewis School of English in Southampton offers English courses for adults and juniors. The school is known for its creative teaching approach, friendly atmosphere and strong focus on speaking and communication.',
        'ar_description' => 'مدرسة لويس للغة الإنجليزية في ساوثهامبتون تقدم دورات للكبار واليافعين. تشتهر المدرسة بأسلوبها الإبداعي في التدريس وأجوائها الودودة وتركيزها القوي على التحدث والتواصل.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'LILA Language School',
        'ar_name' => 'معهد لايلا للغة الإنجليزية',
        'slug' => 'LILA Language School',
        'description' => 'LILA Language School is a modern English school in Liverpool. It offers a wide range of English programmes and university pathways, with stylish facilities and a young, international student community.',
        'ar_description' => 'معهد لايلا للغة الإنجليزية هو معهد حديث في مدينة ليفربول. يقدم مجموعة واسعة من برامج اللغة الإنجليزية ومسارات للجامعات مع مرافق عصرية وبيئة طلابية شبابية دولية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 8]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Live Language School',
        'ar_name' => 'مدرسة لایف لانغويج',
        'slug' => 'Live Language School',
        'description' => 'Live Language School in Glasgow offers English courses in a friendly, community-focused setting. Students learn in small classes and benefit from support with study, work and life in Scotland.',
        'ar_description' => 'مدرسة لايف لانغويج في غلاسكو تقدم دورات في اللغة الإنجليزية في بيئة ودودة تركز على المجتمع. يتعلم الطلاب ضمن فصول صغيرة ويحصلون على دعم يتعلق بالدراسة والعمل والحياة في اسكتلندا.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 9, 19, 20]),
        'rating' => 5.0,
    ],
    [
        'name' => 'LSI Education',
        'ar_name' => 'معهد إل إس آي للتعليم',
        'slug' => 'LSI Education',
        'description' => 'LSI Education runs English language schools in several countries, including the UK. The centres offer general English, academic English and exam preparation, with international classes and modern learning resources.',
        'ar_description' => 'يدير معهد إل إس آي للتعليم مدارس للغة الإنجليزية في عدة دول من بينها المملكة المتحدة. تقدم المراكز دورات إنجليزية عامة وأكاديمية ودورات تحضير للامتحانات مع فصول دولية وموارد تعلم حديثة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'LSI/IH Portsmouth',
        'ar_name' => 'معهد أي إتش بورتموث',
        'slug' => 'LSI/IH Portsmouth',
        'description' => 'LSI/IH Portsmouth is a well-respected school in the coastal city of Portsmouth. It specialises in adult English courses, including general English, exam preparation and professional English for work.',
        'ar_description' => 'معهد أي إتش بورتموث مدرسة ذات سمعة طيبة في مدينة بورتموث الساحلية. يتخصص المعهد في دورات اللغة الإنجليزية للبالغين، بما في ذلك الدورات العامة، ودورات الامتحانات، والإنجليزية المهنية للعمل.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 8, 14]),
        'rating' => 5.0,
    ],
    [
        'name' => 'MC Academy',
        'ar_name' => 'أكاديمية إم سي',
        'slug' => 'MC Academy',
        'description' => 'MC Academy in Manchester offers English courses for international students at different levels. The academy focuses on helping learners reach their academic, professional and personal goals through supportive teaching.',
        'ar_description' => 'أكاديمية إم سي في مانشستر تقدم دورات في اللغة الإنجليزية للطلاب الدوليين في مستويات مختلفة. تركز الأكاديمية على مساعدة المتعلمين في تحقيق أهدافهم الأكاديمية والمهنية والشخصية من خلال تعليم داعم.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Nacel English School London',
        'ar_name' => 'مدرسة ناسيل للغة الإنجليزية لندن',
        'slug' => 'Nacel English School London',
        'description' => 'Nacel English School London is a friendly school located in North London. It offers general English and exam preparation courses with small classes and personal attention for each student.',
        'ar_description' => 'مدرسة ناسيل للغة الإنجليزية في لندن هي مدرسة ودودة تقع في شمال لندن. تقدم دورات عامة في اللغة الإنجليزية ودورات تحضير للامتحانات مع فصول صغيرة واهتمام فردي بكل طالب.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'NCG (New College Group)',
        'ar_name' => 'مجموعة نيو كولِج',
        'slug' => 'NCG (New College Group)',
        'description' => 'NCG – New College Group operates English language schools in several UK cities. Students can choose from general English, IELTS preparation and academic pathway programmes in modern campuses.',
        'ar_description' => 'تدير مجموعة نيو كولِج NCG عدداً من معاهد اللغة الإنجليزية في مدن مختلفة داخل المملكة المتحدة. يمكن للطلاب اختيار دورات عامة، أو دورات تحضير لاختبار IELTS، أو برامج مسارات أكاديمية في حُرم حديثة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Oxford International English Schools OIES',
        'ar_name' => 'مدارس أوكسفورد إنترناشونال للغة الإنجليزية',
        'slug' => 'Oxford International English Schools OIES',
        'description' => 'Oxford International English Schools (OIES) offer English programmes in several UK locations. The schools provide general English, exam courses and junior programmes with a strong focus on student welfare.',
        'ar_description' => 'تقدم مدارس أوكسفورد إنترناشونال للغة الإنجليزية برامج في عدة مدن بريطانية. توفر المدارس دورات إنجليزية عامة ودورات امتحانية وبرامج لليافعين مع اهتمام كبير برفاهية الطالب.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 13, 14]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Oxford International Study Centre',
        'ar_name' => 'معهد أوكسفورد إنترناشونال ستادي سنتر',
        'slug' => 'Oxford International Study Centre',
        'description' => 'Oxford International Study Centre is an independent college in Oxford. It offers English language courses, academic preparation and bespoke programmes for individuals and small groups.',
        'ar_description' => 'معهد أوكسفورد إنترناشونال ستادي سنتر هو معهد مستقل في مدينة أوكسفورد. يقدم دورات في اللغة الإنجليزية، وبرامج إعداد أكاديمي، وبرامج خاصة مصممة للأفراد والمجموعات الصغيرة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Preston Academy of English',
        'ar_name' => 'معهد بريستن أكاديمي للغة الإنجليزية',
        'slug' => 'Preston Academy of English',
        'description' => 'Preston Academy of English is a language school in the city of Preston. It offers English courses for adults and young learners, with friendly teachers and support for adapting to life in the UK.',
        'ar_description' => 'معهد بريستن أكاديمي للغة الإنجليزية هو معهد لغات في مدينة بريستن. يقدم دورات إنجليزية للكبار واليافعين مع مدرسين ودودين ودعم لمساعدة الطلاب على التكيّف مع الحياة في المملكة المتحدة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 22]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Select English Cambridge',
        'ar_name' => 'معهد سليكت إنجلش كامبردج',
        'slug' => 'Select English Cambridge',
        'description' => 'Select English Cambridge is a family-run school close to the centre of Cambridge. It offers English courses for adults and juniors in a safe residential neighbourhood.',
        'ar_description' => 'معهد سليكت إنجلش كامبردج هو معهد عائلي قريب من مركز مدينة كامبردج. يقدّم دورات في اللغة الإنجليزية للكبار واليافعين في حي سكني آمن وهادئ.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'South & City College Birmingham',
        'ar_name' => 'كلية ساوث آند سيتي برمنغهام',
        'slug' => 'South & City College Birmingham',
        'description' => 'South & City College Birmingham is a large further education college that also provides English language support. International students can study English alongside vocational or academic programmes.',
        'ar_description' => 'كلية ساوث آند سيتي برمنغهام هي كلية كبيرة للتعليم المستمر وتقدم أيضاً دعماً في اللغة الإنجليزية. يمكن للطلاب الدوليين دراسة اللغة الإنجليزية إلى جانب برامج مهنية أو أكاديمية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Southbourne School of English',
        'ar_name' => 'معهد ساوثبورن للغة الإنجليزية',
        'slug' => 'Southbourne School of English',
        'description' => 'Southbourne School of English is a family-run school in Bournemouth. It welcomes adults and juniors and offers homestay accommodation close to the school in a quiet residential area.',
        'ar_description' => 'معهد ساوثبورن للغة الإنجليزية هو معهد عائلي في بورنموث. يستقبل الكبار واليافعين ويوفر سكن عائلي قريب من المدرسة في منطقة سكنية هادئة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 9, 8]),
        'rating' => 5.0,
    ],
    [
        'name' => 'St Giles International',
        'ar_name' => 'معهد سانت جाइलز الدولي',
        'slug' => 'St Giles International',
        'description' => 'St Giles International operates English schools in several UK cities. The schools offer a range of programmes, from adult intensive English to junior summer courses in prestigious locations.',
        'ar_description' => 'يدير معهد سانت جایلز الدولي عدداً من مدارس اللغة الإنجليزية في مدن مختلفة داخل المملكة المتحدة. تقدم المدارس برامج متنوعة من الدورات المكثفة للكبار إلى الدورات الصيفية لليافعين في مواقع مميزة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 8]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Stafford House',
        'ar_name' => 'معهد ستافورد هاوس',
        'slug' => 'Stafford House',
        'description' => 'Stafford House runs English language schools in London, Cambridge and Canterbury. The schools provide modern classrooms, residence options and a variety of English and academic programmes.',
        'ar_description' => 'يشغّل معهد ستافورد هاوس مدارس للغة الإنجليزية في لندن وكامبردج وكانتربري. توفر المدارس فصولاً حديثة وخيارات سكن مختلفة ومجموعة متنوعة من برامج اللغة والبرامج الأكاديمية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3, 8]),
        'rating' => 5.0,
    ],
    [
        'name' => 'The London School of English',
        'ar_name' => 'معهد لندن للغة الإنجليزية',
        'slug' => 'The London School of English',
        'description' => 'The London School of English is one of the oldest accredited English schools in the UK. It specialises in adult and professional English courses with a strong focus on quality and customer service.',
        'ar_description' => 'يعد معهد لندن للغة الإنجليزية من أقدم المعاهد المعتمدة في المملكة المتحدة. يتخصص في دورات اللغة الإنجليزية للبالغين والمهنيين مع تركيز قوي على الجودة وخدمة العملاء.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Twin English Centre',
        'ar_name' => 'معهد توين إنجلش سنتر',
        'slug' => 'Twin English Centre',
        'description' => 'Twin English Centre has schools in London and other locations. It offers English language courses, work experience options and junior programmes for groups and individuals.',
        'ar_description' => 'يمتلك معهد توين إنجلش سنتر مدارس في لندن ومواقع أخرى. يقدم دورات في اللغة الإنجليزية وخيارات للتدريب العملي بالإضافة إلى برامج لليافعين للأفراد والمجموعات.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'UK College of English',
        'ar_name' => 'معهد اللغة الإنجليزية في المملكة المتحدة',
        'slug' => 'UK College of English',
        'description' => 'UK College of English is a London-based school offering English courses for adults. The college focuses on interactive lessons, modern facilities and central accommodation options.',
        'ar_description' => 'معهد اللغة الإنجليزية في المملكة المتحدة هو معهد يقع في لندن ويقدم دورات للغة الإنجليزية للبالغين. يركز المعهد على دروس تفاعلية ومرافق حديثة وخيارات سكن في مواقع مركزية.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Westbourne Academy',
        'ar_name' => 'معهد ويستبورن أكاديمي',
        'slug' => 'Westbourne Academy',
        'description' => 'Westbourne Academy is a friendly English school in Bournemouth. It offers general English and exam preparation courses, with homestay and residential options in a pleasant suburb.',
        'ar_description' => 'معهد ويستبورن أكاديمي هو معهد ودود للغة الإنجليزية في بورنموث. يقدم دورات عامة ودورات تحضير للامتحانات مع خيارات سكن عائلي وسكن طلابي في ضاحية لطيفة.',
        'logo' => null,
        'accreditation_ids' => json_encode([2, 3]),
        'rating' => 5.0,
    ],
    [
        'name' => 'Wimbledon School of English',
        'ar_name' => 'مدرسة ويمبلدون للغة الإنجليزية',
        'slug' => 'Wimbledon School of English',
        'description' => 'Wimbledon School of English is a highly regarded English language school in London. It offers a wide range of courses and has a strong academic reputation with students from many countries.',
        'ar_description' => 'مدرسة ويمبلدون للغة الإنجليزية هي من المدارس ذات السمعة الممتازة في لندن. تقدم مجموعة واسعة من الدورات وتتمتع بسمعة أكاديمية قوية، حيث تستقبل طلاباً من دول عديدة حول العالم.',
        'logo' => null,
        'accreditation_ids' => json_encode([]),
        'rating' => 5.0,
    ],
];

// then in your seeder:
DB::table('schools')->insert($schools);

    }
}
